Gh 56 mock blockchain
pyrsia/pyrsia pull request #128
Opened 2021-12-17 19:27 UTC by chb0github

The error I get:

```bash
error[E0515]: cannot return reference to temporary value
  --> pyrsia_node/src/block_chain/block_chain.rs:34:9
   |
34 |            &mut BlockChain {
   |  __________^____-
   | | _________|
   | ||
35 | ||             blocks: vec![]
36 | ||         }
   | ||         ^
   | ||_________|
   | |__________returns a reference to data owned by the current function
   |            temporary value created here

warning: variable does not need to be mutable
   --> pyrsia_node/src/main.rs:215:9
    |
215 |     let mut bc = BlockChain::new();
    |         ----^^
    |         |
    |         help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

```

2021-12-17 19:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pyrsia/pyrsia?pullRequest=128) it.</sub>

2021-12-17 19:34 UTC, chb0github commented
I'd like to get a compiling integration checked in, and then immediately iterate on doing it better. 

I full accept my understanding of blockchain is incomplete

2021-12-17 19:39 UTC, prince-chrismc commented
the chrono library has a vulnerability, https://github.com/pyrsia/pyrsia/runs/4564598702?check_suite_focus=true#step:3:26 try using the time crate directly

2021-12-17 19:43 UTC, prince-chrismc commented on pyrsia_node/src/block_chain/block_chain.rs
> +        &mut BlockChain {
Typically the `new` should look like this

```suggestion
    pub fn new() -> Self {
        BlockChain {
```

When you instantiate something you _always_ expect the caller to take ownership.

The new `BlockChain` instance allocated on line 34 will be destroyed on line 37 so the caller can not have a reference to the memory (that the compiler is trying to return).

2021-12-17 19:47 UTC, prince-chrismc commented on pyrsia_node/src/main.rs
> +use crate::block_chain::block_chain::BlockChain;
I think the `crate` is extra since we have the `mod` 🤔 

```suggestion
use block_chain::{block::Block, block_chain::BlockChain};
```

2021-12-17 19:50 UTC, prince-chrismc commented
1. Please give your PR a more descriptive title... something like "Outline for a mock blockchain"
2. Can you link the issue (so that GitHub knows what to do). You can check out https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2021-12-17 20:37 UTC, chb0github commented on pyrsia_node/src/main.rs
> +use crate::block_chain::block_chain::BlockChain;
It wouldn't compile without, and my editor suggested it. I'll try again

2021-12-17 20:37 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +        &mut BlockChain {
I orginally had this but that gave me other issues. Will retry

2021-12-17 20:38 UTC, chb0github commented
@prince-chrismc - by putting GH-XXX in the title, GH seems to link to it - but you are saying an explicit URL in the title?

2021-12-17 21:33 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +        &mut BlockChain {
@chb0github The problem is that you are returning a reference to the struct you instantiated. The struct itself has to go away when it goes out of scope.  Return the struct, not a reference to it, and then ownership moves to the caller.

2021-12-17 21:53 UTC, prince-chrismc commented
I mean linking it so that Github can automatically close the issue when the PR is merged,
The textual link is automatically added in the commit messages when merging (you dont need to add it manually here)

2021-12-17 22:06 UTC, prince-chrismc commented
Please consider https://github.com/chb0github/pyrsia/pull/1

2021-12-17 22:08 UTC, prince-chrismc commented on pyrsia_node/src/block_chain/block_chain.rs
> +            println!("{}", pretty_json);
We have been trying to use the logging function over print to console 😄

2021-12-20 18:24 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +        &mut BlockChain {
Yeah, I spend hours this weekend aligning my mind to ownership. I fixed it. It's not as I want it to be, but it works.

2021-12-20 18:25 UTC, chb0github commented on pyrsia_node/src/main.rs
> +use crate::block_chain::block_chain::BlockChain;
```
215 |     let mut bc = BlockChain::new();
    |                  ^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
37  | use crate::block_chain::block_chain::BlockChain;
    |

error[E0422]: cannot find struct, variant or union type `Block` in this scope
   --> pyrsia_node/src/main.rs:259:37
    |
259 |                         let block = Block{
    |                                     ^^^^^ not found in this scope
    |

```
When I do as you suggest

2021-12-20 18:26 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +            println!("{}", pretty_json);
Done.

2021-12-20 18:40 UTC, prince-chrismc commented on pyrsia_node/src/main.rs
> +use crate::block_chain::block_chain::BlockChain;
Your right.

I opened a PR but did not change my suggestion here... correct code is https://github.com/chb0github/pyrsia/pull/1/files#diff-2c5d9cbb9033cbd429ad804a903684afdac3c2f5cb96bd0c474b56f0793521fbR39-R40

Thanks for running CI, it passed https://github.com/chb0github/pyrsia/actions/runs/1594267461 🚀

2021-12-20 19:57 UTC, prince-chrismc commented on pyrsia_node/src/main.rs
> +use super::block_chain::{block::Block, block_chain::BlockChain};
I think the reason it's failing is this new line you added. 

Bad communication. I should have resolved my suggestion but everything was good with my PR 

try removing it

```suggestion
```

2021-12-20 20:01 UTC, prince-chrismc commented on pyrsia_node/Cargo.toml
> +chrono = "0.4"
dont forget to remove this =)

2021-12-20 20:07 UTC, mgrand commented
@chb0github The first payload that we will need the blockchain to have is identities. There will be others. The data in the block should be an array of JSON objects.

The identity struct is currently defined in pyrsia_node::node_manager::model::identity. (model will be moving to pyrsia_client_lib)

Because it is annotated with 
`#[signed_struct]`
it implements the `Signed` trait. This trait, with the help of the  `#[signed_struct]` macro, provides some methods you will be interested in:
* `json` returns the signed json associated with the struct.
* `from_json_string` is a static method to create a struct from signed JSON
* `sign_json` creates the JSON representation of the struct and adds a signature. If there is already signed JSON, then it just adds a signature.
* `verify_signatures` verifies the signatures in a struct's JSON and returns information about the signatures.

Identities provide information about public signing key that identifies the signing key.

I assume that you will eventually annotate the Block struct with `#[signed_struct]` so that commit nodes can sign the blocks. This will allow 

I have identified at least two signing keys that will need to be put in the genesis block as part of blockchain creation:
* Blockchain blocks should be signed so that when a non-consensus non-commit node receives a new blockchain block it can verify the the block has a valid signature. The identity used by the commit nodes to sign the blocks should be in the genesis block with some metadata that indicates it is authorized to sign committed blocks.
* The metadata manager is going to have some built-in metadata. This will need to be signed by us. The identity we use to sign it should also be in the genesis block.

2021-12-20 21:30 UTC, fishseabowl commented
I agree with Mark's comment. At the beginning, we could only support centralized commit nodes.

2021-12-20 23:38 UTC, prince-chrismc approved these changes
LGTM!

Please sign the CLA and update your title 👍

2021-12-20 23:40 UTC, prince-chrismc commented on pyrsia_node/src/block_chain/block_chain.rs
> +    pub(crate) fn dump(&self) -> Result<String, Error> {
Is the crate context needed?

```suggestion
    pub fn dump(&self) -> Result<String, Error> {
```

2021-12-21 00:32 UTC, MitaliBo commented on pyrsia_node/src/main.rs
> +                        let block = Block {
i am assuming this is just a template because we are not doing anything with message?

2021-12-21 00:35 UTC, MitaliBo approved these changes

2021-12-21 00:43 UTC, prince-chrismc requested changes
Blocking because the CLA is not being required

2021-12-21 00:44 UTC, prince-chrismc approved these changes
Nevermind, just some bad image caching

2021-12-21 13:48 UTC, mgrand approved these changes
I had a few comments.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +    pub fn genesis(&mut self) -> &mut Self {
Should the genesis function also have crate scope? It sounds like something that would be called internally as part of blockchain initialization. It is not clear that there is a use for external calls to it.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +    pub(crate) fn dump(&self) -> Result<String, Error> {
@prince-chrismc Why are you concerned about the crate scope? This appears to be a method to use for dumping out the contents of the blockchain. At this point, it is perfectly reasonable to not want to expose it as part of the Blockchain's public API.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +        }
@chb0github This raises the interesting question of what should our strategy be if a node has an invalid blockchain. Would you like to organize a team discussion about that, or would you rather I do it?

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +        // let block = self.mk_block( data.clone()).expect("error creating block");
Did you mean to leave this commented line in the code?

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +                let (nonce, hash) = mine_block(last_block.id, now, &last_block.hash, &data);
We do not need to mine blocks. If there is consensus on all of the transactions in the data (which should be an array of JSON objects) then that should be sufficient. The signing format we are using allows for multiple signatures to be present for a single JSON object. Proof of consensus could be the presence of a signature (or signatures?) on a JSON object whose public key (the public key is part of the signature) identifies an identity on the blockchain that includes an attribute identifying it as authorized to certify consensus.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block.rs
> +    pub nonce: u64,
Since we are not mining (everything we are recording on the blockchain has an independent existence outside of the blockchain), it is not clear that there is a need for a nonce.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +            warn!("block with id: {} has wrong previous hash", block.id);
If code detects a situation for which I do not have a way to recover or continue normal operations, I usually call that an error rather than a warning.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +        if block.id != previous_block.id + 1 {
This is OK for now. The the production blockchain, I would like to see the sequence of blocks be based on physical ordering in storage rather than being part of the blockchain's internal data structure. Keeping the block sequence dependent on something external to the blockchain structure is more secure.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +    fn is_chain_valid(&self, chain: &[Block]) -> bool {
I don't see a call to this function. What is the policy for when this should be called and what to do if it returns false?

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +        Err(_) => panic!("SystemTime before UNIX EPOCH!"),
I don't see why system time before the UNIX epoch is a reasonable threshold for panic. If the concern is that the time predates Pyrsia, then the panic threshold should be if it is before this year.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +fn mine_block(id: u64, timestamp: u128, previous_hash: &str, data: &str) -> (u64, String) {
We will rely on signatures rather than mining.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block_chain.rs
> +    let mut hasher = Sha256::new();
I would like to see us use a more secure hash. Please consider BLAKE3. It requires less effort to compute than SHA3-512 and is about as secure.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/main.rs
> +    bc.genesis();
Shouldn't the decision to create a genesis block be internal to the blockchain? Perhaps new should call it if there is no local blockchain.

2021-12-21 13:48 UTC, mgrand commented on pyrsia_node/src/main.rs
> +                        let block = Block {
I assume this is a temporary mechanism for pushing blocks to a node.

2021-12-21 17:13 UTC, chb0github commented on pyrsia_node/src/main.rs
> +                        let block = Block {
Yeah, this is just a "hey, insert block from another node, here"

2021-12-21 17:13 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +    pub fn genesis(&mut self) -> &mut Self {
I actually wanted it to be part of the `new`, but my limited rust was getting in the way. I definitely think it should be cooked in

2021-12-21 17:19 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +        }
Rallying the troops at this point will be on me. There are any number of strategies for reconcilliation - some short term and focused on MVP and others more production grade.

2021-12-21 17:19 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +        // let block = self.mk_block( data.clone()).expect("error creating block");
no. But please don't make me change it - then I would need 3 approvals again

2021-12-21 17:21 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +    let mut hasher = Sha256::new();
Once we have a more concrete block we all agree on, I'll happily change it. This was just for demonstration purposes.

2021-12-21 17:22 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +fn mine_block(id: u64, timestamp: u128, previous_hash: &str, data: &str) -> (u64, String) {
Ok. Then we'll have to talk about the implementation.

2021-12-21 17:24 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +        Err(_) => panic!("SystemTime before UNIX EPOCH!"),
This was ripped right out of rust example docs - the reason they return an `either/Result` is because you can't count on the system time to be monotonically increasing. I mean, I can change this to `.expect("we went back in time")`

2021-12-21 17:29 UTC, chb0github commented on pyrsia_node/src/block_chain/block_chain.rs
> +                let (nonce, hash) = mine_block(last_block.id, now, &last_block.hash, &data);
Obviously we need a consensus phase. I am taking down a lot of notes for this next iteration to resolve

2021-12-21 17:30 UTC, chb0github commented on pyrsia_node/src/main.rs
> +    bc.genesis();
Yes. Again, my limited rust was getting in the way. When you call `BlockChain::new` I expect the genesis block is in place.

2021-12-21 17:31 UTC, merged

2021-12-21 17:31 UTC, chb0github commented
I have taken notes and will address each of these inputs - Thanks all.