Metadata implementation
pyrsia/pyrsia pull request #143
Opened 2021-12-22 14:36 UTC by mgrand

This is an initial implementation of the metadata manager. All features for the demo are implemented, except for those that require the document store to support range searches or updates.

2021-12-22 16:36 UTC, chb0github commented on pyrsia_node/src/node_manager/model/artifact.rs
> +    pub fn hash(&self) -> &Vec<u8> {
I don't understand this code - struct fields can't be made private (I don't think) - so why have all these public getters?

2021-12-22 16:37 UTC, chb0github reviewed
There is 1 bit of code I don't get.

2021-12-22 18:21 UTC, mgrand commented on pyrsia_node/src/node_manager/model/artifact.rs
> +    pub fn hash(&self) -> &Vec<u8> {
@chb0github I want instances of this struct to be immutable. Struct fields are private by default. They can be made public.

2021-12-22 21:52 UTC, prince-chrismc reviewed
Some of the diff are so massive they dont render by default.
![image](https://user-images.githubusercontent.com/16867443/147159236-458a12be-58a4-472d-bc74-0c0ddb41d940.png)

This is a pretty good indication your file needs to be split into smaller chunks
:arrow_right: Please break out the 5 or 6 types into separate files please!

2021-12-22 21:52 UTC, prince-chrismc commented on pyrsia_node/src/node_manager/model/package_type.rs
> +use std::string::ToString;
I dont see `ToString` being used 🤔 

```suggestion
```

2021-12-22 21:52 UTC, prince-chrismc commented on pyrsia_node/src/document_store/document_store.rs
> +    pub fn insert(&self, document: &str) -> Result<(), Box<dyn std::error::Error>> {
It would be nice to have renames like this in separate PRs, this one adds a ton a clutter to the code review.

That being said I do prefer this name.

2021-12-22 21:57 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
> +const FLD_PACKAGE_TYPES_NAME: &str = "name";
I would really discourage from writing documentation to explain the variable names.

https://github.com/pyrsia/pyrsia/pull/136#discussion_r772736415

```suggestion
const DOCUMENT_STORE_PACKAGE_TYPES: &str = "package_types";
const INDEX_PACKAGE_TYPES_NAMES: &str = "names";
const FIELD_PACKAGE_TYPES_NAME: &str = "name";
```

Please these should not be convoluted and hidden.

2021-12-22 22:21 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
> +fn open_document_store(
https://github.com/pyrsia/pyrsia/pull/136#discussion_r772780018

I must not have been clear. Your answer is not touch on the point I was trying to get across. So let me try again.

:arrow_right: I think most of this logic can be moved to `document_store.rs`.

I suggest having a new function that handles
1. checking if it already exists
2. creating it if it does not exist

I would expect this function to become (more of less -- it's untested pseudo code)

```rust
DocumentStore::open_document_store(name, index_spec);
populate_with_initial_records(&ds, initial_records)?;
Ok(ds)
```

Every single owner of a document store needs to implement the previously mentions bullet points

2021-12-22 22:21 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
> +fn failed_to_create_document_store(ds_name: &str, error: Box<dyn Error>) -> Result<DocumentStore> {
It seems excessive to write a function thats only called one to "format an error"

2021-12-22 22:21 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
>  pub trait MetadataApi {
Other than the `MetadataManager` who else will implement this trait?

I assume the answer is nothing ➡️  Now that the code exists I think we should remove this.

I am not comfortable with the "API" in the name ... it leads me to think this shouldn't exist

2021-12-22 22:21 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
> +// TODO move trust manager trait and its default implementation to a separate module
Please move this!

2021-12-22 22:21 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
> +    Ok(())
Should we fail if there are zero?

2021-12-22 22:23 UTC, prince-chrismc commented
Does this address #95  ?

2021-12-22 22:23 UTC, prince-chrismc commented on pyrsia_node/src/metadata_manager/metadata.rs
>  pub trait MetadataApi {
https://github.com/rust-lang/api-guidelines/discussions/28#discussioncomment-233414

2021-12-22 22:56 UTC, betarelease requested changes
Let us not add the date time parsing into the main repo. Once we change to using a crate please create an updated PR.

2021-12-22 22:56 UTC, betarelease commented on pyrsia_node/pyrsia_client_lib/src/iso8601.rs
> +fn iso8601_format_spec() -> Vec<FormatItem<'static>> {
We should not have our own implementation of Date/Time.

Please use a suitable crate.

2021-12-22 23:08 UTC, mgrand commented on pyrsia_node/pyrsia_client_lib/src/iso8601.rs
> +fn iso8601_format_spec() -> Vec<FormatItem<'static>> {
@betarelease I would happily use the Chrono crate that handles all of ISO8601 parsing and formatting, except that there is a security vulnerability associated with this. According to cargo audit, there is no version available to fix this.
For this reason we have our own. 

You marked as requiring changes. I cannot proceed without your approval now. I know of no crate other than chrono (I did spend quite a bit of time looking) that does what need.  I am unable to proceed until you approve.

2021-12-23 00:27 UTC, prince-chrismc commented on pyrsia_node/pyrsia_client_lib/src/iso8601.rs
> +fn iso8601_format_spec() -> Vec<FormatItem<'static>> {
The CVE comes from the time library which is an optional feature of chrono.
Have you tried changing which feature we enable? to not pull in this deprecate version?

![image](https://user-images.githubusercontent.com/16867443/147169681-fae89b86-999a-4bc0-9233-d9aa590a3e60.png)

From the chrono README

> The oldtime feature is enabled by default for backwards compatibility, but future versions of Chrono are likely to remove the feature entirely.

https://github.com/chronotope/chrono/blob/3467172c31188006147585f6ed3727629d642fed/README.md#L91

https://github.com/chronotope/chrono/blob/f6bd567bb677262645c1fc3131c8c1071cd77ec3/Cargo.toml#L31
https://crates.io/crates/time/0.1.44

2021-12-23 00:46 UTC, mgrand commented on pyrsia_node/pyrsia_client_lib/src/iso8601.rs
> +fn iso8601_format_spec() -> Vec<FormatItem<'static>> {
@betarelease @prince-chrismc The problem is not with being able to represent time. We are using a standard `time` crate for that. The issue is being able to parse and format ISO-8601 dates. That is what we had to implement ourselves.

2021-12-23 02:33 UTC, prince-chrismc commented on pyrsia_node/pyrsia_client_lib/src/iso8601.rs
> +fn iso8601_format_spec() -> Vec<FormatItem<'static>> {
You said https://github.com/pyrsia/pyrsia/pull/143#discussion_r774224940

> I would happily use the Chrono crate that handles all of ISO8601 parsing and formatting, except that there is a security vulnerability associated with this.

So let's try some more solution!

2021-12-23 19:02 UTC, closed without merging