Efrisch/gossipsub Added gossipsub file-transfer topic for magnet links
pyrsia/pyrsia pull request #169
Opened 2021-12-28 22:07 UTC by efrisch

2021-12-28 22:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=169) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pyrsia/pyrsia?pullRequest=169) it.</sub>

2021-12-28 22:48 UTC, mgrand reviewed
I left some comments.

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/main.rs
> +    let gossip_topic: libp2p::gossipsub::IdentTopic = libp2p::gossipsub::IdentTopic::new("pyrsia-file-share-topic");
This is getting to be a very long method. Perhaps you could move your code to a separate method or function.

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/main.rs
> +        new_swarm(gossip_topic.clone(), floodsub_topic.clone(), transport, local_key, respond_tx)
The usual way to reference this in Rust would be `swarm::new`. That is the Rust convention. Because it was called new_swarm, I thought it was defined locally until I found the `use`.

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/main.rs
> +                        println!("{}", swarm.behaviour_mut().gossipsub_mut().publish(gossip_topic.clone(), cmd).unwrap())
From within the pyrsia node, we should be using the log crate for this sort of thing. Perhaps instead of 
`println!`
use
`info!`

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/network/behavior.rs
> +            let msg_data: String = String::from_utf8(message.data).unwrap();
If unwrap fails, it panics. If message.data is not valid UTF8, I think it would be better to log an error and return.

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/network/swarm.rs
> +    gossip_topic: IdentTopic,
This is large enough to break up into smaller methods.

2021-12-28 22:48 UTC, mgrand commented on pyrsia_node/src/network/swarm.rs
> +        .message_id_fn(message_id_fn) // content-address messages. No two messages of the
shouldn't you be passing the message to the function rather than itself?

2021-12-28 22:49 UTC, mgrand approved these changes

2021-12-28 23:55 UTC, prince-chrismc commented on pyrsia_node/src/network/swarm.rs
> +    local_key: identity::Keypair,
Why are there no change in main? I'd expect the main to low it's usage of `PeerId` 

❓ Are we running with two ids?
❓ Whats the old one doing (in main)?

2021-12-28 23:55 UTC, prince-chrismc commented on tests/test_code_coverage.sh
> +docker run --rm --security-opt seccomp=unconfined -it code_coverage:1.0
Looks like merge conflicts

```suggestion
docker build --no-cache -t code_coverage:2.0 -f ./tests/code_coverage.Dockerfile .
docker run --rm --security-opt seccomp=unconfined -it code_coverage:2.0
```

2021-12-28 23:56 UTC, prince-chrismc commented on pyrsia_node/src/network/behavior.rs
> +                println!("Start downloading {}", msg_data);
node should not be printing to console =)

```suggestion
                info!("Start downloading {}", msg_data);
```

2021-12-28 23:56 UTC, prince-chrismc commented on pyrsia_node/src/main.rs
> +                        println!(
```suggestion
                        info!(
```

2021-12-28 23:58 UTC, prince-chrismc commented on pyrsia_node/src/network/swarm.rs
> +    local_key: identity::Keypair,
Might be out of scope but I'd of expected this to be a member I guess... It's error prone to "extract" the id in multiple places.

https://github.com/pyrsia/pyrsia/blob/44022d8d429c8b0d31a02c42dd37e612e9ffcba2/pyrsia_node/src/main.rs#L229

2021-12-28 23:58 UTC, prince-chrismc reviewed
small nits about printing to console

2021-12-28 23:59 UTC, prince-chrismc commented
Please sign the CLA

2021-12-29 13:58 UTC, efrisch commented on pyrsia_node/src/network/swarm.rs
> +    local_key: identity::Keypair,
We're using the same peer_id with two topics. One is floodsub, one is gossipsub; but both share the public key. Which is what this is doing. Open to changes if there's a better approach. We can discuss.

2021-12-29 13:59 UTC, efrisch commented on tests/test_code_coverage.sh
> +docker run --rm --security-opt seccomp=unconfined -it code_coverage:1.0
I deliberated changed this back to version 1.0; I was having an issue on my machine with 2.0 - and we explicitly use `--rm` with docker run so the version should never increment.

2021-12-29 14:00 UTC, efrisch commented on pyrsia_node/src/network/behavior.rs
> +                println!("Start downloading {}", msg_data);
This was a placeholder. But a logger statement serves as well. Changed.

2021-12-29 14:07 UTC, efrisch commented on pyrsia_node/src/network/swarm.rs
> +        .message_id_fn(message_id_fn) // content-address messages. No two messages of the
That's a message id function (not a message itself); it gets invoked to generate a message id on every message and ensures uniqueness.

2021-12-29 14:07 UTC, efrisch commented on pyrsia_node/src/main.rs
> +                        println!(
Also changed.

2021-12-29 14:10 UTC, efrisch commented
> Please sign the CLA

Done. Thought I was covered by contractual relationship with jfrog. Easy enough to be explicit about it.

2021-12-29 14:16 UTC, mgrand submitted a review, later dismissed

2021-12-29 14:31 UTC, mgrand submitted a review, later dismissed

2021-12-29 17:19 UTC, prince-chrismc requested changes

2021-12-29 17:19 UTC, prince-chrismc commented on .github/workflows/cla.yml
> +name: "CLA Assistant"
What is this?

2021-12-29 17:21 UTC, prince-chrismc commented
Please delete the new workflow. You must have been out sick when I presented it to the team.

You (and any future contributors) only need to follow the comment that is posted in our PR
https://github.com/pyrsia/pyrsia/pull/169#issuecomment-1002300469 for example.

2021-12-29 17:23 UTC, prince-chrismc commented on tests/test_code_coverage.sh
> +docker run --rm --security-opt seccomp=unconfined -it code_coverage:1.0
That not what `--rm` does 😕 

"remove" only cleans up the container not the image that is created.

What issue did you have? when creating an image you can give it any name. There's likely a bigger issue if you can not change the name.

2021-12-29 17:24 UTC, prince-chrismc commented on pyrsia_node/src/network/swarm.rs
> +    local_key: identity::Keypair,
Let me make this a new issue.

error prone code == bad

2021-12-29 17:37 UTC, efrisch commented on tests/test_code_coverage.sh
> +docker run --rm --security-opt seccomp=unconfined -it code_coverage:1.0
code_coverage is the name 2.0 is a tag. 2.0 implies there was a 1.0 tag that isn't published. I guess I want to know why we would skip 1.0 and jump to 2.0? If you really feel strongly about it I'll investigate further into the issue I had.

From `docker build --help`, `-t, --tag list                Name and optionally a tag in the 'name:tag' format`

2021-12-29 17:41 UTC, efrisch commented on .github/workflows/cla.yml
> +name: "CLA Assistant"
https://jfrog.slack.com/archives/C02GCU7PE8L/p1639173359470100?thread_ts=1639173356.470000&cid=C02GCU7PE8L

2021-12-29 18:13 UTC, prince-chrismc commented on tests/test_code_coverage.sh
> +docker run --rm --security-opt seccomp=unconfined -it code_coverage:1.0
We will never publish this. It's just a local test image.
I changed the version because I changed the internal structure and broke the API on the image.

Let's remove version (and the confusion) seems like its worse to have it

```suggestion
docker build --no-cache -t code_coverage -f ./tests/code_coverage.Dockerfile .
docker run --rm --security-opt seccomp=unconfined -it code_coverage
```

2021-12-29 18:16 UTC, prince-chrismc commented on .github/workflows/cla.yml
> +name: "CLA Assistant"
But if you read the thread... I said we should not do that. I also share a video demonstrating the working CLA 😕

2021-12-29 19:24 UTC, chb0github commented on pyrsia_node/src/network/swarm.rs
> +    let message_id_fn = |message: &GossipsubMessage| {
This closure doesn't have anything it's capturing - it could be a top-level function

2021-12-29 19:25 UTC, chb0github commented on tests/test_code_coverage.sh
> +docker build --no-cache -t code_coverage -f ./tests/code_coverage.Dockerfile .
We could achieve this with a `docker-compose.yaml` file.

2021-12-29 19:25 UTC, chb0github approved these changes

2021-12-29 19:44 UTC, prince-chrismc approved these changes

2021-12-29 19:46 UTC, prince-chrismc commented
Seems like a random failure?

https://github.com/pyrsia/pyrsia/runs/4661021813?check_suite_focus=true#step:5:409

"happy path run for more than 60s" 😖

2021-12-29 20:42 UTC, merged