Add new block definition for discuss
pyrsia/pyrsia pull request #179
Opened 2021-12-30 23:21 UTC by fishseabowl

I would add methods and traits later. Welcome any suggestions.

2021-12-30 23:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/pyrsia/pyrsia?pullRequest=179) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: fishseabowl<br/>:x: Xuefei Han<br/><hr/>**Xuefei Han** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pyrsia/pyrsia?pullRequest=179) it.</sub>

2021-12-31 00:24 UTC, chb0github commented on pyrsia_node/src/block_chain/block.rs
> +pub struct block {
Upper case please

2021-12-31 00:25 UTC, chb0github commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
How about we just call these `signature`? They are identical.

Also, I was thinking that the signature should include a crypto challenge

2021-12-31 00:25 UTC, chb0github requested changes
see comments

2021-12-31 14:06 UTC, mgrand submitted a review, later dismissed

2021-12-31 14:06 UTC, mgrand commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
@fishseabowl @chb0github The data that we store will be JSON that has its own signature. See the `Signed` trait in `pyrsia_node/pyrsia_client_lib/src/signed.rs`.  I would like to see the blockchain rely on the signature in the JSON.

The signers of the JSON will be signing their JSON outside of the node. It is unclear who would add another signature when we store the JSON in the blockchain.   

I think it will be safe to assume that all data stored on the blockchain will be a struct that implements the `Signed` trait. This means that the struct has a signed JSON object associated with it. The trait includes methods for verifying the signature and for getting the JSON.

For examples see the unit tests that the end of `pyrsia_node/pyrsia_client_lib/src/signed.rs` and also in 
`pyrsia_node/pyrsia_client_lib/signed_struct/tests/lib.rs`

The first type of data that we will want to store on the block chain is an identity. These will be instances of the `Identity` struct at `pyrsia_node/src/node_manager/model/identity.rs`.

The `Identity` struct has a `public_key` field which will serve as the primary key for the identity. We will need to be able to quickly retrieve identities by their public key. We will also need to be able to update the information in an identity, subject to signature constraints. We will eventually also need to be able to retrieve historical identity records rather than just the current identity information.

2021-12-31 15:40 UTC, fishseabowl commented on pyrsia_node/src/block_chain/block.rs
> +pub struct block {
Good comments. Thanks.

2021-12-31 18:19 UTC, fishseabowl commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
> How about we just call these `signature`? They are identical.
> 
> Also, I was thinking that the signature should include a crypto challenge

Yes. Maybe they are identical, maybe not. I would create Signature struct and also have two alias name TransactionSignature and BlockSignature.

2021-12-31 18:56 UTC, fishseabowl commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
@mgrand Thanks for your comments. 1. I just think identity is only part of business logic, so these could be stored in transaction.payload. 2. Converting between different data formats interface would be provided.

2021-12-31 19:00 UTC, fishseabowl commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
@mgrand I am not sure your goal looks like DID(Decentralized identifiers). Maybe hyperledger indy is a good reference.

2021-12-31 19:48 UTC, mgrand commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
I am not familiar with Hyperledger Indy. I will take a look. Thank you for mentioning it

2021-12-31 19:51 UTC, mgrand commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
Even though transactions are signed, blocks will also need to be signed. The originator of the transaction or signed struct will sign that. The committing node will need to sign the block. 

The reason that we need the committer to sign the block is that the blocks will be propagated to non-commiter and non-consensus node using an insecure mechanism. Signing the blocks allows us to detect any attempts to introduce bogus blocks into the Pyrsia network.

2021-12-31 20:09 UTC, mgrand commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
@fishseabowl I took a quick look at Indy. It is interesting, but not what we need. I see two areas where its goals are different than ours:
* It assumes that all identity providers provide information using the same interoperable format. We need to accommodate diverse and heterogeneous sources of identity information.
* It features, "Zero Knowledge Proofs which prove that some or all of the data in a set of Claims is true without revealing any additional information, including the identity of the Prover"  Because we are trying to create a process that automates trust, we need everything about an identity claim to be transparent.

2022-01-01 00:34 UTC, fishseabowl commented on pyrsia_node/src/block_chain/block.rs
> +pub struct TransactionSignature {
@mgrand Thanks for your comment. Hyperledger Indy have some good features: 1. Delegate 2. Revoke. It may be helpful.  Otherwise, I think ZKP just want to leverage transparent and privacy.

2022-01-04 18:09 UTC, prince-chrismc commented on pyrsia_node/src/block_chain/block.rs
> +pub struct Header {
For this to be stored as JSON we could use you help answering a few questions (please open a PR showing how to complete the following)

- Serialize custom type (e.g `Address`)
  - Is this a custom type or just an alias
  - Are arrays of ints going to be `[ 1, 2, 2]`
  - How could we just a HTTP safe string thats base64 encoded from this?
  - How can we get a hex encoded version of this value?

This would be a great issue for you to open and pick up ❤️

2022-01-04 18:11 UTC, chb0github commented on pyrsia_node/src/block_chain/block.rs
> +pub struct Block_v1 {
Just replace `Block` - we don't need a `v....` - I realize this would mean the app won't compile, but if we are going to use your structs, then it's going to have to all be back ported anyways.

Please just overwrite `Block` and call it done

2022-01-04 18:20 UTC, prince-chrismc commented
You need to fix the commit authorship for the CLA. See https://github.com/pyrsia/pyrsia/pull/179#issuecomment-1003210392

2022-01-04 18:21 UTC, prince-chrismc commented
Looking over this, I agree the structure is a great step. Please continue with https://github.com/pyrsia/pyrsia/pull/179#discussion_r778288955 and updating the rest of the code (or leave a few todos)

2022-01-04 18:30 UTC, prince-chrismc commented
I think the signing is out of scope for this PR. Let's get something working.

2022-01-04 18:38 UTC, chb0github commented
My assumption is that this code/struct would be integrated into the code base. Even if you have to rip out everything and just stub it to make it compile. We need to move forward

2022-01-04 19:00 UTC, fishseabowl commented
> I think the signing is out of scope for this PR. Let's get something working.

At first, I would directly use libp2p::identity::ed25519::Keypair to sign and verify.

2022-01-05 19:05 UTC, chb0github commented
Xuefe, will you be merging this in?

2022-01-05 22:56 UTC, prince-chrismc commented
Moving this as draft since there are lot of merge conflicts 😱 this will give you time to fix it 👍

2022-01-06 00:13 UTC, closed without merging

2022-01-06 04:39 UTC, prince-chrismc commented
replaced by #192 🤔