Move Blockchain Definition and related methods to new crate
pyrsia/pyrsia pull request #323
Opened 2022-02-04 02:40 UTC by fishseabowl

1. Add header, block, and blockchain definition and related methods
2. Add read, add block to file functions

2022-02-04 17:36 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +                let transaction = pyrsia_blockchain_network::block::Transaction::new(
Can we import this and reduce the name spacing

2022-02-04 17:36 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +                && previous_commiter == local_id{
Weird newline

2022-02-04 17:37 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +    let g_block = GenesisBlock::new(key);
I don't think you should be treating the genesis block as exceptional. It's a normal block with hardcoded values

2022-02-04 17:38 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +        Some(v) => v,
You could just use `expect` here and shortcut the match

2022-02-04 17:39 UTC, chb0github commented on src/blockchain/src/block.rs
> +    pub transactions: Vec<Transaction>,
Is there something like a `SortedSet` in rust? If we use a sorted set then these transactions will naturally stay sorted.

2022-02-04 17:40 UTC, chb0github commented on src/blockchain/src/block.rs
> +        verify(
You have 1 verify function call another? I don't get it

2022-02-04 17:40 UTC, chb0github commented on src/blockchain/src/blockchain.rs
> +impl Default for Config {
This is interesting - what does this do?

2022-02-04 17:41 UTC, chb0github commented on src/blockchain/src/blockchain.rs
> +pub struct GenesisBlock {
We don't need a callout block for genesis

2022-02-04 17:41 UTC, chb0github commented on src/blockchain/src/blockchain.rs
> +    pub genesis_block: GenesisBlock,
There are just blocks

2022-02-04 17:42 UTC, chb0github requested changes
I have a few comments. We want this to be our "clean" impl. People will look

2022-02-04 17:49 UTC, prince-chrismc requested changes
Blocker: We need to remove the old code (since most of these files are copies)

Please try to remove the `pyrsia_blockchain_network` from the name to keep it clean

2022-02-04 17:49 UTC, prince-chrismc commented on src/blockchain/Cargo.toml
> +#libp2p = {git = "https://github.com/libp2p/rust-libp2p.git", rev = "e15dad5f45a9ae804b7a27bd6f885a1b00e0525a", features=["tcp-tokio"]}
```suggestion
```

2022-02-04 17:49 UTC, prince-chrismc commented on src/blockchain/src/header.rs
> +pub struct Header {
You forgot to remove the old code 

https://github.com/pyrsia/pyrsia/blob/385d406acf217d27ea9939a98a6a670084cadecc/src/block_chain/header.rs

2022-02-04 17:49 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +use tokio::io::{self, AsyncBufReadExt};
Following christians idea we can skip this name

```suggestion
use tokio::io::{self, AsyncBufReadExt};
use pyrsia_blockchain_network::*;
```

2022-02-04 17:49 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let id_keys = pyrsia_blockchain_network::blockchain::generate_ed25519();
```suggestion
    let id_keys = blockchain::generate_ed25519();
```

2022-02-04 17:49 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +        &pyrsia_blockchain_network::block::get_publickey_from_keypair(&ed25519_keypair).encode(),
```suggestion
    let local_id = header::hash(
        &block::get_publickey_from_keypair(&ed25519_keypair).encode(),
```

2022-02-04 17:59 UTC, prince-chrismc reviewed
# Ideas for future work

I'll open these as issues when this is merged!

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    struct MyBehaviour {
I'd like to give this a better name, maybe

```suggestion
    struct BlockchainNetworkBehaviour {
```

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    impl NetworkBehaviourEventProcess<FloodsubEvent> for MyBehaviour {
It would be ideal to move this to a seperate file so we have less conflicts when we do #322 

I have a lot grouped into https://github.com/prince-chrismc/pyrsia-sandbox/blob/aleph-substrate-node/src/block_chain/network.rs which might be something we can do before

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +                println!("++++++++++");
We should replace these with the logging library we have used in the rest of the project!

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let ed25519_keypair = match id_keys {
We should only focus on one key. Directly using `identity::Keypair::Ed25519` we can refactor later to use the generic enum version

Thoughts?

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let g_block = GenesisBlock::new(key);
> I don't think you should be treating the genesis block as exceptional. It's a normal block with hardcoded values

This is something we can explore when we do #322 👍

2022-02-04 17:59 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +    signature: Vec<u8>,
It would be nice if we can use the edwards key library like I had done https://github.com/prince-chrismc/pyrsia-sandbox/blob/a9333aced792e1017db1f424eb1b4b77c7803aa4/src/block_chain/crypto.rs#L28

This way there will be less conflicts for #322

2022-02-04 18:08 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +    let ed25519_keypair = match id_keys {
Go for it

2022-02-04 19:05 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +                let transaction = pyrsia_blockchain_network::block::Transaction::new(
Good comments. I would update it.

2022-02-04 22:01 UTC, prince-chrismc approved these changes
My blockers have been addressed 🚀

2022-02-04 22:03 UTC, prince-chrismc commented on src/blockchain/src/blockchain.rs
> +impl Default for Config {
This is one of the trendy rust patterns that exists... instead of having a ctor

https://rust-unofficial.github.io/patterns/idioms/default.html

2022-02-04 22:14 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +                println!("++++++++++");
Absolutely. I would add log and debug information.

2022-02-04 22:16 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +    let ed25519_keypair = match id_keys {
Yes. It is just for backward compatible with Pyrsia

2022-02-04 22:32 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +    let g_block = GenesisBlock::new(key);
I store the configuration information in the genesis block. I would refactor these codes to make them clearer.

2022-02-05 03:51 UTC, prince-chrismc submitted a review, later dismissed

2022-02-05 04:28 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +    pub transactions: Vec<Transaction>,
Maybe like https://doc.rust-lang.org/stable/std/collections/struct.BTreeSet.html

This is an excellent point to discuss!

Thinking a little bit, I dont think the order of transactions matters 🤔 we are looking at starting with an AURA so only one node will commit and to my knowledge other nodes wont challenge the block based on the transactions inside.

Also with Aleph there will only be a linear graph so it should be less of a problem at the block level.

Great Explore/Spike issue 👍

2022-02-05 04:37 UTC, prince-chrismc commented
There's two small comments that should be addressed in this PR

https://github.com/pyrsia/pyrsia/pull/323#discussion_r799676881
https://github.com/pyrsia/pyrsia/pull/323#discussion_r799678207

***

@chb0github, can we save https://github.com/pyrsia/pyrsia/pull/323#discussion_r799679109 for a follow up PR?
My code has a complete different the notion of the genesis block and I think it might be worth making changes with #322 since we'll need to discuss and decide what we want.

Thoughts?

2022-02-07 17:48 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let g_block = GenesisBlock::new(key);
Christian, good for following this up in an issue

He'd like to have the genesis block ad index 0 in the blockchain, maybe a special transaction?

***

Xuefei, when we have a "sync initialize" when nodes join this can go away (since only one node will make the configuration)

2022-02-07 17:50 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let g_block = GenesisBlock::new(key);
moved to #329

2022-02-07 17:56 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +    pub transactions: Vec<Transaction>,
Error prone, can solve the duplicated transaction being recorded.

e.g the same message being routed to us twice from network

2022-02-07 17:59 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +    pub transactions: Vec<Transaction>,
moved to #331

2022-02-07 18:06 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +        verify(
I agree this is a little awkward. but we need to change this for #322 so let's leave it alone for now 🙈

2022-02-07 18:07 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    struct MyBehaviour {
```suggestion
    # TODO(prince-chrismc): Give this a much better name!
    struct MyBehaviour {
```

2022-02-07 18:12 UTC, prince-chrismc commented on src/blockchain/src/block.rs
> +    signature: Vec<u8>,
moved to #333

2022-02-07 18:12 UTC, prince-chrismc submitted a review, later dismissed

2022-02-07 18:13 UTC, prince-chrismc commented
We all approved!

![image](https://user-images.githubusercontent.com/16867443/152847203-374605f2-44cb-447f-8a03-0667587ad327.png)

2022-02-07 18:44 UTC, betarelease commented
This particular PR also has a lot of commits that are point in time but need to be squashed to 4-5 meaningful commits. I am not able to find a conversation that created a another ticket - since this PR is too long.

2022-02-07 18:45 UTC, betarelease commented
Also if the three of you are working together, shouldn't we wait for someone outside the three of you to approve as well?

2022-02-07 18:47 UTC, betarelease commented
Github tweeted this trick to reduce noise from merge commits

https://twitter.com/github/status/1489672242074206209?s=20&t=bBtLBVUZabSAlSrMCKWf3w

2022-02-07 18:49 UTC, prince-chrismc commented
> I am not able to find a conversation that created a another ticket - since this PR is too long.

Please follow slack, I already enabled this on the repo

https://openssf.slack.com/archives/C0302CVKPA5/p1644000250494039

2022-02-07 20:58 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    impl NetworkBehaviourEventProcess<FloodsubEvent> for MyBehaviour {
Moved to #332

2022-02-07 20:59 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +                println!("++++++++++");
```suggestion
                println!("++++++++++"); // TODO(fishseasbowl): Replace with logging methods
```

2022-02-07 21:00 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let ed25519_keypair = match id_keys {
Moved to #333

2022-02-07 23:55 UTC, prince-chrismc commented
After a quick zoom call,

> reduce noise from merge commits

We'll make sure to not open PRs with messy, unhelpful commits so are to not pollute the reader. Team effort to help with this.

I will manually be merging this... at at that time I can fixup the message that will be made so regardless of what's in the PR it will look pretty. 👍

2022-02-08 01:41 UTC, merged