Breakdown development workflow from PR template
pyrsia/pyrsia pull request #430
Opened 2022-02-28 23:27 UTC by prince-chrismc

This moves most of the "Code Contributions" check boxes to a separate file with more details about setting up your system.

I also flipped the order so it's less circular.

2022-03-02 03:50 UTC, prince-chrismc commented
I asked @AbhijithGanesh for help writing a small script that will complement the leaner template.
https://github.com/pyrsia/pyrsia/issues/437

2022-03-02 18:40 UTC, sbtaylor15 approved these changes
Looks good.  Easier to follow with changes that were made.

2022-03-08 19:04 UTC, chb0github commented on .github/pull_request_template.md
> +- [ ] I've requested a review  from "pyrsia/collaborators"
If this isn't automated, it won't happen. Just saying

2022-03-08 19:05 UTC, chb0github submitted a review, later dismissed

2022-03-08 22:15 UTC, prince-chrismc commented on .github/pull_request_template.md
> +- [ ] I've requested a review  from "pyrsia/collaborators"
It hard to automate "everything is ready for others to be assigned" there's a gap between "it's open for feedback" and "I am done working" 🤔

2022-03-09 14:41 UTC, efrisch approved these changes
I found a few typos and corrected them. The only thing I feel we may want to revisit is something like:
[ ] I have run the "pre-commit.sh" or "pre-commit.bat" script and it completes with no errors or warnings.

Thoughts?

Otherwise 👍 🪨 🎸

2022-03-09 23:51 UTC, prince-chrismc commented
The "pre-commit" script is too heavy for the majority, I think only code contributors should consider it as a sanity check incase they are unsure of the development flow.

2022-03-11 21:32 UTC, prince-chrismc commented
> I found a few typos and corrected them.

Teamwork makes the dreamwork!

2022-03-14 18:04 UTC, betarelease approved these changes
Added a couple of minor comments. Once you address them this can be merged.

2022-03-14 18:04 UTC, betarelease commented on .github/pull_request_template.md
> +This PR does... by accomplishing ... and it can be review by ...
`it can be reviewed by...`

2022-03-14 18:04 UTC, betarelease commented on .github/pull_request_template.md
> +- [ ] I've built the code `cargo build --workspace`.
This should be replaced by `precommit.sh` ?

2022-03-14 18:04 UTC, betarelease commented on docs/dev_workflow.md
> +When developing new features for Pyrsia, we aim for the best quality code possible. Here's the steps with some "How To"s on getting there.
Thanks for adding and improving this section. This was missing and as we added I was falling behind on what is the next item I should install.

2022-03-14 18:36 UTC, prince-chrismc commented on .github/pull_request_template.md
> +This PR does... by accomplishing ... and it can be review by ...
```suggestion
This PR does... by accomplishing ... and it can be reviewed by ...
```

2022-03-14 18:37 UTC, prince-chrismc commented on .github/pull_request_template.md
> +- [ ] I've built the code `cargo build --workspace`.
Discussed above https://github.com/pyrsia/pyrsia/pull/430#issuecomment-1063494936

TL;DR - it too heavy for the most contributors

2022-03-22 18:26 UTC, AbhijithGanesh requested changes

2022-03-22 18:26 UTC, AbhijithGanesh commented on .github/pull_request_template.md
> +Fixes pyrsia/pyrsia#
I think there must be a space

`Fixes pyrsia/pyrsia #`

2022-03-22 18:26 UTC, AbhijithGanesh commented on .github/pull_request_template.md
> +- [ ] I've built the code `cargo build --workspace`.
I agree with Christopher here.

2022-03-22 21:11 UTC, prince-chrismc commented on .github/pull_request_template.md
> +Fixes pyrsia/pyrsia#
🤔 no this is the full syntax from https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword



Issue in a different repository | KEYWORD OWNER/REPOSITORY#ISSUE-NUMBER | Fixes octo-org/octo-repo#100
-- | -- | --

2022-03-24 18:16 UTC, AbhijithGanesh approved these changes

2022-03-24 18:17 UTC, merged