Use sccache for faster builds and split os/x and linux into separate jobs
pyrsia/pyrsia pull request #451
Opened 2022-03-02 18:19 UTC by sbtaylor15

## PR Checklist

- [X] I've built the code `cargo build`. For major changes, `cargo build --workspace --release` is recommended.
- [X] I've run the automated unit tests `cargo test`. This executes our automated unit tests.
- [X] I've not broken any existing tests or functionality. In addition to `cargo test`, I've run `cargo clippy`
- [X] I've not introduced any new known security vulnerabilities. I've run `cargo audit`

- [ ] I've included a brief description and a good title of the proposed changes and how to test them.
- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've associated an [issue](https://github.com/pyrsia/pyrsia/issues) with this Pull Request. 
- [ ] I've checked that the code is up-to-date with the `pyrsia/main` branch.
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've assigned this Pull Request to "pyrsia/collaborators"

## Description

Fixes pyrsia/pyrsia#389

Implemented sccache to speed up builds.  This is done by removing the `cargo check` commands and consolidating the `cargo build --workspace` and `cargo build --tests` into a script that will run both commands at the same time in the background utilizing sccache.  

Moved the scripting from the rust.yaml to .sh files in order to keep the rust.yaml readable.  

The initial run with fresh empty cache is ~25mins and from an existing cache ~10-15mins.  Cache is recreated when the md5 of the Cargo.lock changes.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/14826572/156423674-f079108b-98ab-4373-a920-05153588bde3.png)

2022-03-02 18:59 UTC, prince-chrismc commented on .github/workflows/rust.yml
>    build:
```suggestion
  build-push-linux:
```

2022-03-04 13:18 UTC, efrisch approved these changes
A few minor suggestions. Otherwise, looks good to me.

2022-03-04 13:18 UTC, efrisch commented on .github/workflows/build.sh
> +$( cargo build --workspace --verbose --release; echo $? > /tmp/ws.rc ) &
Do we have GNU parallel? https://www.gnu.org/software/parallel/

2022-03-04 13:18 UTC, efrisch commented on .github/workflows/sccache-macos.sh
> +curl -o- -sSLf https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-apple-darwin.tar.gz | tar xzf -
I think `tar -C` would let you skip the `mv`.

2022-03-04 15:11 UTC, sbtaylor15 commented on .github/workflows/build.sh
> +$( cargo build --workspace --verbose --release; echo $? > /tmp/ws.rc ) &
I need to check what GitHub Actions have installed from the base OS.

2022-03-04 15:12 UTC, sbtaylor15 commented on .github/workflows/sccache-macos.sh
> +curl -o- -sSLf https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-apple-darwin.tar.gz | tar xzf -
Ok, I will give tar -C a test

2022-03-04 21:50 UTC, efrisch submitted a review, later dismissed
👍

2022-03-07 17:36 UTC, prince-chrismc commented
This breaks the required check this they are renamed, holding of on approving

2022-03-08 19:08 UTC, chb0github commented on .github/workflows/build.sh
> +rc=$(cat /tmp/ws.rc /tmp/tests.rc | sort -nr | head -n1)
Purpose? If one returned `10` and the other `22` you'd have this return `22` - but `22` is a return code specific to the app that failed. Also, what happens if they are the same? I think being explicit about the error (with `stderr`) and some output, would be best. Returning the code is fine.

2022-03-08 19:10 UTC, chb0github commented on .github/workflows/sccache-linux.sh
> +mkdir -p /home/runner/.cargo/bin 2>/dev/null
I'll advised. You could error for any reason - not just because it already exists. 
better would be: `test -f ... || mkdir`

I am not sure what error you think is ok from this code.

2022-03-08 19:18 UTC, chb0github commented on .github/workflows/sccache-linux.sh
> +
please add `-e` so if anything doesn't work the shell script errors out

2022-03-08 19:19 UTC, chb0github commented on .github/workflows/sccache-linux.sh
> +curl -o- -sSLf https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz | tar --strip-components=1 -C /home/runner/.cargo/bin -xzf -
You have `-f` here but don't check the status code and don't have `-e` at the top of the shell script. The error is being entirely ignored

2022-03-08 19:19 UTC, chb0github commented on .github/workflows/sccache-macos.sh
> +
`set -e`

2022-03-08 19:19 UTC, chb0github requested changes
I think some better error handling in the bash scripts would be positive

2022-03-09 01:39 UTC, sbtaylor15 commented on .github/workflows/build.sh
> +rc=$(cat /tmp/ws.rc /tmp/tests.rc | sort -nr | head -n1)
We need to check if either background process threw an error.  If so then fail the GitHub Step.  The value of the rc is not important as long as it is not equal to 0 to indicate an error.  

Added a few more echo lines in the latest commit to display the rc of each job to help with determining which background process had an error.

2022-03-14 20:04 UTC, sbtaylor15 commented on .github/workflows/sccache-linux.sh
> +mkdir -p /home/runner/.cargo/bin 2>/dev/null
Added set -e and extra checks file exist checks

2022-03-14 20:04 UTC, sbtaylor15 commented on .github/workflows/sccache-linux.sh
> +curl -o- -sSLf https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz | tar --strip-components=1 -C /home/runner/.cargo/bin -xzf -
Added set -e and extra checks file exist checks

2022-03-14 20:06 UTC, sbtaylor15 commented on .github/workflows/sccache-macos.sh
> +
Added set -e and extra checks file exist checks

2022-03-15 16:14 UTC, efrisch submitted a review, later dismissed
👍

2022-03-16 21:19 UTC, prince-chrismc approved these changes
Bring this up at the standup so everyone knows they'll need to rebase for their PRs once it's merged 🚀

2022-03-24 16:44 UTC, prince-chrismc commented
https://github.com/pyrsia/pyrsia/pull/481 add the `--all-targets` which need to be updated here (hence the merge conflicts)

2022-03-24 17:17 UTC, sbtaylor15 commented
> #481 add the `--all-targets` which need to be updated here (hence the merge conflicts)

@prince-chrismc Does the `cargo build --tests` need the `--all-targets` as well?

2022-03-26 00:40 UTC, chb0github commented on .github/workflows/sccache-linux.sh
> +test -f  /home/runner/.cargo/bin || mkdir -p /home/runner/.cargo/bin 2>/dev/null
You don't need to test, mkdir will return 0 for this case:

```
christianb@christianb-mac ~ % mkdir delme
christianb@christianb-mac ~ % mkdir -p delme 
christianb@christianb-mac ~ % echo $?
0
```

2022-03-26 00:41 UTC, chb0github commented on .github/workflows/sccache-macos.sh
> +test -f /Users/runner/.cargo/bin || mkdir -p /Users/runner/.cargo/bin
No need to test. And, I think `curl` will make the path for you if it doesn't exist

2022-03-26 00:41 UTC, chb0github submitted a review, later dismissed

2022-03-26 08:01 UTC, AbhijithGanesh approved these changes
LGTM

2022-03-28 16:53 UTC, sbtaylor15 commented on .github/workflows/sccache-macos.sh
> +test -f /Users/runner/.cargo/bin || mkdir -p /Users/runner/.cargo/bin
The curl command is sending the output to stdout and piped into tar.  tar does not create the directory specified by -C.  That directory must exist therefore the mkdir is necessary.

2022-03-28 18:47 UTC, sbtaylor15 commented on .github/workflows/sccache-linux.sh
> +test -f  /home/runner/.cargo/bin || mkdir -p /home/runner/.cargo/bin 2>/dev/null
Removed the `test -f`

2022-03-29 20:41 UTC, prince-chrismc approved these changes
Sold!

2022-03-30 02:11 UTC, AbhijithGanesh approved these changes

2022-03-30 18:32 UTC, merged

2022-03-30 18:33 UTC, betarelease commented
we had to update the build checks to refer to the new ones from this PR. Also we ignored codecov for this specific case since this one does not change code but how the infra is laid out.

@sbtaylor15 @betarelease