Demo tutorial
pyrsia/pyrsia pull request #541
Opened 2022-03-30 15:24 UTC by erwin1

## Description

This PR does documents the demo flow and it can be reviewed by reading and following the described steps.

## PR Checklist

- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've included a good title and brief description along with how to review them.
- [ ] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from "pyrsia/collaborators"

### Code Contributions

- [ ] I've built the code `cargo build --workspace`.
- [ ] I've run the unit tests `cargo test --workspace`.

2022-03-30 19:14 UTC, mseabornIBM commented
We should add links to the Pyrsia install to the steps. I had to go hunt them down to install. It would also be nice to add some information about why I need to install two nodes. I know it is obvious but other may not.

2022-03-31 18:11 UTC, mseabornIBM approved these changes

2022-04-08 06:28 UTC, AbhijithGanesh commented on docs/tutorials/demo.md
> +> ```
Shouldn't this be `rm -rf`

2022-04-08 06:28 UTC, AbhijithGanesh submitted a review, later dismissed

2022-04-08 06:45 UTC, erwin1 commented on docs/tutorials/demo.md
> +> ```
you mean without `#` ? That is the root prompt which I included everywhere (to indicate root `#` or regular user `$`) 
it might make sense to remove those everywhere, but I'll leave that for another pass.

2022-04-08 10:22 UTC, erwin1 commented on docs/tutorials/demo.md
> +> # rf -rf /usr/local/var/pyrsia
```suggestion
> # rm -rf /usr/local/var/pyrsia
```

2022-04-08 10:24 UTC, erwin1 commented on docs/tutorials/demo.md
> +> ```
I failed to see that I wrongly typed `rf` instead of `rm` - fixed it

2022-04-08 10:29 UTC, AbhijithGanesh approved these changes
LGTM

2022-04-08 10:29 UTC, AbhijithGanesh commented on docs/tutorials/demo.md
> +- We assume you have docker installed. Follow these instructions https://docs.docker.com/engine/install/ubuntu/ if you do not.
```suggestion
- We assume you have docker installed. Follow these [instructions](https://docs.docker.com/engine/install/ubuntu/) if you do not.
```

2022-04-08 10:29 UTC, AbhijithGanesh commented on docs/tutorials/demo.md
> +```
I would like this to be moved up(in the page)

2022-04-08 12:25 UTC, erwin1 commented on docs/tutorials/demo.md
> +```
Where would you place it?
We can't do it before Pyrsia is installed. And this is right after installation. (I could place it right before 'Use the CLI to check the node status' but I think it makes sense that stays the next step right after installation.

2022-04-08 12:33 UTC, erwin1 commented
Thanks @AbhijithGanesh for your comments. I addressed most of them and made another change/simplification.

2022-04-08 17:10 UTC, erwin1 commented
I think this should be good to be merged once I can get a couple of re-approvals (approvals gets removed on new commits)

2022-04-08 17:11 UTC, mseabornIBM approved these changes
These changes make sense I will be using it over the weekend to setup my own integration tests.

2022-04-08 17:13 UTC, erwin1 commented
Thanks. You might also be interested in https://github.com/pyrsia/pyrsia/pull/553

2022-04-08 18:20 UTC, chb0github commented on docs/tutorials/demo.md
> +```mermaid
This is a new format to me!

2022-04-08 20:09 UTC, chb0github reviewed
You know what would be super hot: An actual demo script, with prompts, etc so the demo is coded and not just text.

2022-04-11 04:16 UTC, AbhijithGanesh submitted a review, later dismissed

2022-04-11 18:53 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +> ```
Let's allow humans to copy-paste

```suggestion
> ```sh
> apt-get remove pyrsia
> rm -rf /usr/local/var/pyrsia
> ```
```

2022-04-11 18:55 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +## Demo steps
```suggestion
## Demo Steps
```

I'd also play with something like

```suggestion
## Demo Breakdown
```

2022-04-11 19:01 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```mermaid
I personal find this huge and daunting 😱

2022-04-11 19:02 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +### Install Pyrsia
We should refer to the website here.... but TBA I guess

2022-04-11 19:03 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +# apt-get update
as above it would be delightful if this could be copy pasted

2022-04-11 19:03 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +# curl -sS https://pyrsia.io/install.sh | sh
as above it would be delightful if this could be copy pasted

2022-04-11 19:03 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +or simply use this script that bundles the above:
I think this should be first

2022-04-11 20:51 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +Disk Space Used:             0.0260%
Can you please also update https://github.com/pyrsia/pyrsia/tree/88c568c6b0de4b5da76912d1a5343678463ee6a8#connecting-with-other-nodes

since it's out of data

2022-04-11 20:51 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
It's not clear where this needs to be added... maybe give the full line so the user can copy paste

2022-04-13 16:55 UTC, fishseabowl commented on docs/tutorials/demo.md
> +  - Node 2 doesn't have to download the image again
Can we use fewer names? Or add more explanations about instance 1, instance 2, node 1 and node 2? I am a little confused about these names.

2022-04-13 17:07 UTC, fishseabowl commented on docs/tutorials/demo.md
> +```
I guess DHT is just implemented internally. It is not exposed to the user. It is better to remove DHT in the demo workflow.

2022-04-13 17:29 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +Disk Space Used:             0.0260%
Duplicate of #460

2022-04-13 18:31 UTC, mseabornIBM requested changes

2022-04-13 18:32 UTC, mseabornIBM submitted a review, later dismissed

2022-04-13 18:34 UTC, mseabornIBM reviewed
See warnings comment.

2022-04-13 18:51 UTC, prince-chrismc commented
I never header of this https://github.com/pyrsia/pyrsia/pull/541#discussion_r845785570 😱

2022-04-15 17:54 UTC, mseabornIBM commented on docs/tutorials/demo.md
> +# curl -sS https://pyrsia.io/install.sh | sh
Also the curl command just hangs on a new install. maybe it is my setup gut weird.

2022-04-15 17:58 UTC, mseabornIBM commented on docs/tutorials/demo.md
> +# curl -sS https://pyrsia.io/install.sh | sh
I cannot browse to https://pyrisa.io/install.sh either. Is the link wrong?

2022-04-18 22:46 UTC, chb0github approved these changes

2022-04-19 12:53 UTC, erwin1 commented on docs/tutorials/demo.md
> +### Install Pyrsia
this was supposed to be a one-stop-demo-tutorial. I think we'll need other ones more specific to our end-users that should refer to the website for installation.

2022-04-19 12:57 UTC, erwin1 commented on docs/tutorials/demo.md
> +or simply use this script that bundles the above:
I don't want to fix this in the context of this documentation issue. I'll create a follow-up for this.

2022-04-19 13:04 UTC, erwin1 commented
> You know what would be super hot: An actual demo script, with prompts, etc so the demo is coded and not just text.

@chb0github this tutorial helps setting up the demo on 2 public instances. I think #560 will come close to a demo script that can be run

2022-04-19 16:28 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +### Install Pyrsia
That's totally fine, we should have the "super easy" option here and say "find more ways here", save us from the duplication.

This will also be on the website so it's worth having good links between pages

2022-04-19 17:02 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +Node1 ->> DHT: Node1 checks if the image is available<br>locally or on the Pyrsia network
There are terms in here at that are not explained and it's confusing since they are not directly in the demo

2022-04-19 17:03 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +deactivate User
There's a "user" in the diagram https://github.com/pyrsia/pyrsia/pull/541/files#diff-d7f70fe397549f11d26eb4b678e7f6817b2fb9dc2e3c1319156139665eccd053R80 so I am not sure the distinction makes sense

2022-04-19 17:04 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +User2 ->> Docker2: docker pull image
Are two people required to perform the demo? Why is there a second user?

2022-04-19 17:06 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
Let's make this easier on the eyes

```suggestion
Edit `/etc/systemd/system/multi-user.target.wants/pyrsia.service`
and add `--peer /ip4/public_ip_of_node1/tcp/44000` to the `ExecStart` line so it looks like this:

```
ExecStart=/usr/bin/pyrsia_node --host 0.0.0.0 -L /ip4/0.0.0.0/tcp/44000 --peer /ip4/public_ip_of_node1/tcp/44000
```
```

2022-04-19 17:07 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
```suggestion
```sh
```

2022-04-19 17:09 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +● pyrsia.service - Pyrsia Node
```suggestion
```sh
service pyrsia status
```

You should see the something similar to following

```sh
$ service pyrsia status
● pyrsia.service - Pyrsia Node
```

2022-04-19 17:09 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
```suggestion
```sh
```

2022-04-19 17:10 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
```suggestion
```sh
```

2022-04-19 17:11 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
This is exactly the same as above

```suggestion
```

2022-04-20 17:55 UTC, erwin1 commented on docs/tutorials/demo.md
> +```
I understand it can be confusing, but the reason I added the DHT to the diagram is to make things more understandable... maybe I simply have to rename it and call it 'Pyrsia network'?

The alternative is that I draw lines from node2 to node1 (because we only have 2 nodes in this demo, we know for a fact that node2 can only talk to node1) but in future scenario's we do need some kind of representation of the 'Pyrsia Network'

2022-04-20 18:35 UTC, erwin1 commented on docs/tutorials/demo.md
> +```mermaid
I attempted to simplify the sequence diagram

2022-04-20 18:36 UTC, erwin1 commented on docs/tutorials/demo.md
> +```
I attempted to simplify the diagram 
@fishseabowl and @prince-chrismc thanks for having another look 🙏

2022-04-20 18:59 UTC, prince-chrismc commented on docs/tutorials/demo.md
> +```
The language is a lot more consistent, I only saw one "node 2" slipping into just "node" but that does not impact clarity.

I like that there is 6 steps (❤️ for the numbers) and 6 activations in the diagram and they are all in the same order/wording

I was able to look at the diagram and click the links for the steps to get the instructions which is very nice 🚀 

I think this is enough for a first pass, I sure someone less familiar will have more comments but this hopefully gives enough clues

2022-04-20 19:01 UTC, prince-chrismc approved these changes
It's clear! Having not been involved this able to lead me along 👏

2022-04-20 20:26 UTC, fishseabowl approved these changes
LGTM 🚀

2022-04-20 22:59 UTC, merged