CLI command restructure and other feedback
pyrsia/pyrsia pull request #558
Opened 2022-04-05 04:12 UTC by MitaliBo

## Description

Fixes pyrsia/pyrsia #554 

This PR implements the feedback points mentioned in #554 
## Screenshots (optional)

## PR Checklist

- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've included a good title and brief description along with how to review them.
- [ ] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [ ] I've built the code `cargo build --all-targets` successfully.
- [ ] I've run the unit tests `cargo test --workspace` and everything passes.

2022-04-08 17:06 UTC, efrisch approved these changes
👍

2022-04-11 17:14 UTC, fishseabowl commented on docs/local_dev_setup.md
> +   OR place the config file in these OS specific locations:
Config file and subcommand "config", which has higher priority?

2022-04-11 17:31 UTC, MitaliBo commented on docs/local_dev_setup.md
> +   OR place the config file in these OS specific locations:
no priority, these are the choices provided to user to choose

2022-04-11 17:52 UTC, fishseabowl commented on docs/local_dev_setup.md
> +   OR place the config file in these OS specific locations:
what to do if the two are different?

2022-04-11 20:59 UTC, prince-chrismc commented on docs/local_dev_setup.md
> +   OR place the config file in these OS specific locations:
Does the subcommand strictly only change the config file? and all other commands exclusive read from the config?

Are there command flags/options that can overrride the config file?

2022-04-11 21:05 UTC, prince-chrismc requested changes
Blocking strictly for the root readme needs to be update with the correct CLI output 🙏 
otherwise just some nits

2022-04-11 21:05 UTC, prince-chrismc commented on docs/local_dev_setup.md
> +   Windows: `{FOLDERID_RoamingAppData}`\\`pyrsia-cli`\\config Ex: C:\Users\<UserName>\AppData\Roaming\pyrsia-cli\config\pyrsia-cli.toml
Use those env to make life easier!

```suggestion
   Windows: %APPDATA%\\Roaming\\pyrsia-cli\\config\\pyrsia-cli.toml
```

2022-04-11 21:05 UTC, prince-chrismc commented on docs/local_dev_setup.md
> +    Total Disk Available:    10.5 GB
Please update the root readme 🙏

2022-04-11 21:05 UTC, prince-chrismc commented on pyrsia_cli/readme.md
> +Run below install command from pyrsia_cli folder which installs the CLI in `~/.cargo/bin`. Make sure `~/.cargo/bin` is included in your `PATH`
```suggestion
Run the install command below from the current `pyrsia_cli/` folder which installs the CLI in `~/.cargo/bin`. Make sure `~/.cargo/bin` is included in your `PATH`.
```

2022-04-11 21:05 UTC, prince-chrismc commented on pyrsia_cli/src/main.rs
> +    let (ls, pg, st) = (
We should avoid custom abbreviations, my brain absolutely got these wrong.

```suggestion
    let (list, ping, status) = (
```

2022-04-12 20:54 UTC, prince-chrismc commented
> Blocking strictly for the root readme needs to be update with the correct CLI output 🙏 otherwise just some nits

This would close https://github.com/pyrsia/pyrsia/issues/460

2022-04-13 10:42 UTC, MitaliBo commented on pyrsia_cli/src/main.rs
> +    let (ls, pg, st) = (
These are just variables being used in the code not in the cli command itself, how does it matter?

2022-04-13 10:53 UTC, MitaliBo commented on docs/local_dev_setup.md
> +   OR place the config file in these OS specific locations:
@fishseabowl you mean that if the user puts a file with wrong content or fields than it will throw parse error.

@prince-chrismc yes only "--config" subcommand make changes to config and there is no particular option to override because this command itself override the content provided by user if the file already exist. The only difference is that user does not need to use this subcommand at all and start directly using any "pyrsia node" as those commands itself trigger the creation of default config file if no file is present. So we can see user to use this subcommand only to override any values

2022-04-13 10:57 UTC, MitaliBo commented on docs/local_dev_setup.md
> +    Total Disk Available:    10.5 GB
Thanks for pointing it out, updated.

2022-04-13 14:19 UTC, fishseabowl approved these changes
LGTM 🚀

2022-04-13 17:25 UTC, prince-chrismc approved these changes

2022-04-13 17:27 UTC, prince-chrismc commented on pyrsia_cli/src/main.rs
> +    let (ls, pg, st) = (
I find them confusing, I did not understand the code reading it twice

2022-04-13 17:56 UTC, merged