Drop in Aleph-BFT consensus into blockchain and example
pyrsia/pyrsia pull request #600
Opened 2022-04-18 20:23 UTC by prince-chrismc

## Description

Fixes pyrsia/pyrsia#322

This PR does... by accomplishing... and it can be reviewed by... you can also test the changes by running...

## Screenshots (optional)

## PR Checklist

- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've included a good title and brief description along with how to review them.
- [ ] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [ ] I've built the code `cargo build --all-targets` successfully.
- [ ] I've run the unit tests `cargo test --workspace` and everything passes.
- [ ] I've made sure my rust toolchain is current `rustup update`.

2022-04-18 20:24 UTC, prince-chrismc commented
@fishseabowl since you asked to peak at the Network behavior

2022-04-18 20:38 UTC, fishseabowl commented
> @fishseabowl since you asked to peak at the Network behavior

@prince-chrismc Thanks for the update. 🚀

2022-04-20 17:49 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +
Could you add more comments about these constants if possible?

2022-04-20 17:55 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +    let edwards_pair = identity::Keypair::Ed25519(id_keys.clone());
ed25519_key is better. Edward algorithm can use different curves.

2022-04-20 18:13 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +const INITIAL_DELAY_MS: u128 = 5000;
a delay of size 128??

2022-04-20 18:14 UTC, chb0github commented on src/blockchain/src/lib.rs
> +    // Our NodeIndex.
Where's your rustdoc?

2022-04-20 18:16 UTC, chb0github commented on src/blockchain/src/lib.rs
> +    for block_num in 1u128.. {
This is quite the long for loop, that also has a while loop. Seems high in cyclomatic complexity.

2022-04-20 18:16 UTC, chb0github commented on src/blockchain/src/lib.rs
> +                    // blocks_for_network
Remove the commented code, please

2022-04-20 18:20 UTC, chb0github commented on src/blockchain/src/providers.rs
> +    dependent_messages: HashMap<Block, Vec<u32>>,
Some commenting on these fields would be nice. I don't actually understand what `dependent_messages` means

2022-04-20 18:21 UTC, chb0github commented on src/blockchain/src/structures/header.rs
> +pub type Ordinal = u128;
Why create a new type? And, and ordinal of u128 is insane - that number is larger than the number of atoms in the universe

2022-04-20 18:21 UTC, chb0github commented on src/blockchain/src/structures/header.rs
> +    pub ordinal: Ordinal,
You added a type alias. No idea why

2022-04-20 18:22 UTC, chb0github requested changes
I would love to be walked through this code - it's much to complicated and lacking in documentation for me to understand what's all going on here

2022-04-20 19:06 UTC, prince-chrismc commented on src/blockchain/src/structures/header.rs
> +    pub ordinal: Ordinal,
Remains of the trial and error trying to clue things together, the compiler provides better feedback when things dont match types versus basics

2022-04-20 19:08 UTC, prince-chrismc commented on src/blockchain/src/lib.rs
> +    for block_num in 1u128.. {
This is just a POC loop that runs forever, this is far too basic for what we actually need long term.
As this code grows/refactors it will get broken down but as of today we have dont what that is.

2022-04-20 19:09 UTC, prince-chrismc commented on src/blockchain/src/lib.rs
> +    // Our NodeIndex.
This is just copy paste from the internet, it does not have any meaning yet to pyrsia

2022-04-20 19:09 UTC, prince-chrismc commented on src/blockchain/src/lib.rs
> +                    // blocks_for_network
This code needs to be implemented in a future issue

2022-04-20 19:10 UTC, prince-chrismc commented on src/blockchain/src/lib.rs
> +                    // let block = Block::new(block_num, config.data_size);
```suggestion
                    // TODO(prince-chrismc): Figure out how to generate new blocks and push them on the network
                    // let block = Block::new(block_num, config.data_size);
```

2022-04-20 19:13 UTC, prince-chrismc commented on src/blockchain/src/providers.rs
> +    dependent_messages: HashMap<Block, Vec<u32>>,
Me Neither! :shrug: it's copy pasted from https://github.com/aleph-zero-foundation/AlephBFT/blob/92ec3cf5b071255ca0f5ba68b18a2a30380fdbec/examples/blockchain/chain/data.rs#L21

We need to tailor this to our requirements later.

2022-04-20 21:35 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +const TXS_PER_BLOCK: usize = 50000;
@fishseabowl asked in the office, writing it here - This is a legacy from the aleph example that was generating fake random bytes.

This is being passed around but not being used anywhere

2022-04-20 21:36 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +const INITIAL_DELAY_MS: u128 = 5000;
Rust did not like mixing u64 and u128 because of the narrowing conversion

2022-04-20 21:39 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +
just left over from the aleph example I started with. https://github.com/aleph-zero-foundation/AlephBFT/blob/92ec3cf5b071255ca0f5ba68b18a2a30380fdbec/examples/blockchain/main.rs#L16. 

It's been awhile but the main POC loop starts making blocks after `INITIAL_DELAY` then makes one block every `BLOCK_TIME`... never figured out what `TX_SIZE` changed

We need to play with these to decided if we keep or change them.

2022-04-20 21:42 UTC, prince-chrismc commented on src/blockchain/src/structures/header.rs
> +pub type Ordinal = u128;
It's the same one that was already there, did not question it. As for the alias, I answered below https://github.com/pyrsia/pyrsia/pull/600#discussion_r854468423

2022-04-20 22:53 UTC, prince-chrismc commented on src/blockchain/examples/simple_node.rs
> +    let edwards_pair = identity::Keypair::Ed25519(id_keys.clone());
```suggestion
    let ed25519_pair = identity::Keypair::Ed25519(id_keys.clone());
```

2022-04-21 18:36 UTC, fishseabowl commented on src/blockchain/examples/simple_node.rs
> +
thanks for the example. 🚀

2022-04-22 17:27 UTC, efrisch approved these changes
Good first start

2022-04-22 17:29 UTC, prince-chrismc commented
We had a zoom meeting https://pyrsia.io/events/ https://calendar.google.com/calendar/u/0/r/week?eid=NWNiaTVia2JhbWRoaTRhNzY1bHY5cHQ1MGYgcHlyc2lhb3BlbnNvdXJjZUBt&ctz=America/Los_Angeles&sf=true

@fishseabowl @prince-chrismc @fishseabowl @chb0github @efrisch @erwin1 @steveonjava participated, I will fix up the PR and we we move to get this merged today 🚀

2022-04-22 18:13 UTC, efrisch approved these changes
👍

2022-04-22 18:25 UTC, chb0github approved these changes

2022-04-22 18:33 UTC, merged