Initial implementation for JSON signatures
pyrsia/pyrsia pull request #62
Opened 2021-12-01 21:12 UTC by mgrand

Create a mechanisms for serializing structs to signed JSON and verifying the signatures.

2021-12-08 22:59 UTC, mgrand commented
Before anyone asks why I have created three new crates, here are the reasons:
* Because signed structs will be needed by both Pyrsia nodes and their clients, we need a library for shared code. For this reason, I created `pyrsia_client_lib`.
* To make signed structs easy to use, I needed to define a procedural macro. Rust requires that procedural macros be in a separate crate by themselves. For his reason, I created `signed_struct`.
* We need to test the macros in `signed_struct`. Rust won't allow the test to be in the same create as the procedural macro. Putting it in `pyrsia_client_lib` makes Cargo complain about a circular dependency. I had to create a separate crate to put the test in. This is why I created `signed_struct_test`.

2021-12-08 23:44 UTC, prince-chrismc requested changes
> here are the reasons

I feel strongly the location of you new crates should be approved upon. 

> their clients, we need a library for shared code

1. CLI should not be doing any "work" signing should be done in the node.
2. "clients" can pick the parts they need from the node.
    - Cargo is **extremely** flexible! You can nest crates in the project structure. [docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies)

> Rust requires that procedural macros be in a separate crate by themselves

Again the does not require it to be at the root of the repository. Cargo is flexible.
First example I found in mozilla github code base: https://github.com/mozilla/gecko-dev/blob/d36cf98aa85f24ceefd07521b3d16b9edd2abcb7/xpcom/rust/xpcom/Cargo.toml#L13

> Rust won't allow the test to be in the same create as the procedural macro

you can run integration tests. https://github.com/ferrous-systems/testing-proc-macros is a great example! You can also read https://doc.rust-lang.org/book/ch11-03-test-organization.html which I used in #80

2021-12-08 23:50 UTC, prince-chrismc commented
I suspect the failures https://github.com/pyrsia/pyrsia/runs/4463970462?check_suite_focus=true#step:4:1267 are because of incorrect changes to the `Cargo.lock`

https://github.com/pyrsia/pyrsia/pull/62/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL533-L538

2021-12-09 02:10 UTC, mgrand commented
@prince-chrismc You wrote
> I feel strongly the location of you new crates should be approved upon.
Ok. Please explain. What don't you like about the current location? If you have a better idea, where to you suggest that they go?

> 1. CLI should not be doing any "work" signing should be done in the node.
Again, what are your reasons for this?

Requiring signing to be done in the node opens a security risk. Do to that would require that we make private keys available to Pyrsia nodes. That is an unnecessary risk of compromising private keys. Because nodes are interacting with other nodes, we have to assume that they will be the target of hackers. Just the fact that private keys are available to nodes makes them more of a target. It will also make people question how secure we are.

Nodes support organizations will be particularly attractive targets. We should keep them out of nodes for this reason alone. 

Another reason to not do signing in nodes is that it would imply that nodes are accepting unsigned data. This opens up another security risk. One simple rule that I think we should follow is that if data is not signed it is not on a Persia node. Allowing unsigned data means that someone who is trying to attack a Pyrsia node can remain anonymous.

> 2. "clients" can pick the parts they need from the node.
>    
>    * Cargo is **extremely** flexible! You can nest crates in the project structure. [docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies)

Yes Cargo is flexible. I fail to understand what the point is that your are trying to make with that. I assume that you have some application of Cargo's flexibility in mind, but I do not know what.

> > Rust requires that procedural macros be in a separate crate by themselves
> 
> Again the does not require it to be at the root of the repository. Cargo is flexible. First example I found in mozilla github code base: https://github.com/mozilla/gecko-dev/blob/d36cf98aa85f24ceefd07521b3d16b9edd2abcb7/xpcom/rust/xpcom/Cargo.toml#L13

Agreed. That is why the procedural macro crate and its test crate are not in the root. They are under pyrsia-client-lib. I do not understand your point.

> you can run integration tests. https://github.com/ferrous-systems/testing-proc-macros is a great example! You can also read https://doc.rust-lang.org/book/ch11-03-test-organization.html which I used in #80

Again, I do not know what you are asking of me. I have not integration tests here. If you consider testing a proc macro an integration test rather than a unit test. I don't what to argue semantics.

Please clarify what it is you want of me. The only change you actually requested, that we do our signing in the nodes, I will not do.

2021-12-09 02:17 UTC, mgrand commented
@prince-chrismc 
> I suspect the failures https://github.com/pyrsia/pyrsia/runs/4463970462?check_suite_focus=true#step:4:1267 are because of incorrect changes to the `Cargo.lock`
I have made no manual changes to Cargo.lock. What I understand from your statement is that your believe that I have somehow done something that resulted in the Cargo.lock file being somehow wrong. I have no idea what to do about this. Any suggestions?  Is there a particular command that I can run in my local environment to replicate the problem?

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +    // To debug this, uncomment the two println! macros and the tokens generated by the macros
Rather than have commented out `println!`, can we switch to the `dbg!` macro?

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                output
clippy thinks you should eliminate the let binding. I think that would go away with a `dbg!` here.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +            field_names.insert(id.to_string());
Since you are iterating the field_names here, couldn't you find the max `_jsonYYY` here rather than 102-110?

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                                impl<'π> ::pyrsia_client_lib::signed::Signed<'π> for #struct_ident<'π> {
I think I remember you telling me you chose π because it was unlikely to appear in JSON; can we document that here. Or is my memory playing tricks on me... regardless; why π?

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                            let output = quote! {
This `quote!` macro is [beautiful](https://docs.rs/quote/latest/quote/).

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                            //println!("Output from signed_struct_derive: {}", output);
`dbg!`?

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +) -> Result<
Congrats! You've triggered a "very complex type used" warning from clippy. Reminds me of "insufficient politeness" from intercal. I wonder if there's a `[Please]` annotation.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +            ty.lifetime = Some(Lifetime::new("'π", Span::call_site()));
I feel like this 'π needs a comment. I find this surprising. What are we doing here? I can almost work it out from context.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +        assert_eq!(result, 4);
This does not feel a particularly high value unit test.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/src/signed.rs
> +//! struct is a that has associated with it a JSON representation of the struct's contents that are
"is a that"? A signed struct has a JSON representation with an embedded verifiable signature field.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/src/signed.rs
> +//! However, it is not recommended that you directly implement the `Signed` trait directly. Instead,
Redundant "directly" at end of sentence.

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/src/signed.rs
> +//! This annotation runs a macro that add some fields to support the Signed trait, implements the
`Signed` trait

2021-12-09 14:43 UTC, efrisch commented on pyrsia-client-lib/src/signed.rs
> +//! this. You should read it.
Redundant "this".

2021-12-09 15:25 UTC, mgrand commented on Cargo.toml
> +    "pyrsia-client-lib"
@efrisch pyrsia-client-lib is a lib crate for code that is needed for both Pyrsia nodes and clients. Clients will want to create and verify signatures. Nodes will want to verify sigantures. There are also some structs that will need to be shared, though they are not yet in there.

2021-12-09 15:53 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +    // To debug this, uncomment the two println! macros and the tokens generated by the macros
@efrisch The dbg! macro will still generate output. I have expanded the comment to further explain. Please let me know if it still does not make sense.

2021-12-09 15:58 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +            field_names.insert(id.to_string());
@efrisch I don't quite understand. I am trying _json0. If it clashes I try _json1, and then _json2 and so on.

2021-12-09 16:11 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                                impl<'π> ::pyrsia_client_lib::signed::Signed<'π> for #struct_ident<'π> {
@efrisch I documented this in the file comment. I wanted to choose something that would be unlikely to clash with another lifetime defined outside the macro. I choose π because in greek, pyrsia is πυρσός.

2021-12-09 16:12 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +                            //println!("Output from signed_struct_derive: {}", output);
That would just generate more voluminous output that would be harder to understand.  See the new improved comment ad the beginning of the file.

2021-12-09 16:13 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +            ty.lifetime = Some(Lifetime::new("'π", Span::call_site()));
@efrisch See the new improved comment at the end of the beginning of file comment.

2021-12-09 16:15 UTC, mgrand commented on pyrsia-client-lib/signed_struct/src/lib.rs
> +        assert_eq!(result, 4);
@efrisch Thank you.

2021-12-09 18:44 UTC, MitaliBo commented on pyrsia-client-lib/src/signed.rs
> +        signed_json_buffer.push_str(jws_string.as_str());
repetitive code can be move out of if-else

2021-12-09 18:44 UTC, MitaliBo commented on pyrsia-client-lib/src/signed.rs
> +        let json = r#"{"boo":true,"number":234,"nul":null, "ob":{"a":123,"b":"str"}, "arr":[3, true, {"sig":"mund", "om":"ega"}, "asfd"] , "extra":"qwoeiru"}"#;
is it better to use json file for testing and move all below tests there?

2021-12-09 20:01 UTC, prince-chrismc commented
None of the new crates should be in the root of the repository. 

They should all be under the `pyrsia_node`

```
pyrsia_node
|_src/
|_signing
   |_src/
   |_signing_macros
      |_src/
      |_tests/
|_tests/
pyrsia_cli/
|_src/
```

2021-12-09 22:20 UTC, mgrand commented on pyrsia-client-lib/src/signed.rs
> +//! struct is a that has associated with it a JSON representation of the struct's contents that are
Fixed.

2021-12-09 22:34 UTC, mgrand commented on Cargo.toml
> +    "pyrsia-client-lib",
fixed

2021-12-09 22:38 UTC, mgrand commented on pyrsia-client-lib/src/signed.rs
> +        signed_json_buffer.push_str(jws_string.as_str());
Thank you. It is done.

2021-12-09 22:50 UTC, mgrand commented on pyrsia-client-lib/src/signed.rs
> +        let json = r#"{"boo":true,"number":234,"nul":null, "ob":{"a":123,"b":"str"}, "arr":[3, true, {"sig":"mund", "om":"ega"}, "asfd"] , "extra":"qwoeiru"}"#;
@MitaliBo Putting the JSON in a file wouldn't help here. I added a comment to better explain what is going on.

2021-12-09 23:13 UTC, prince-chrismc approved these changes

2021-12-10 15:39 UTC, efrisch approved these changes
👍

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/signed_struct/src/lib.rs
> +/// The generated impls and their methods use a lifetime named 'π. This greek letter was chosen
💯

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/src/lib.rs
> +#![allow(mixed_script_confusables)] // This is to allow structs created by a derive macro to have private fields that begin with the grek letter π
Confusables! 🥇

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/src/signed.rs
> +//! This annotation runs a macro that add some fields to support the Signed trait, implements the
Missing \` around Signed.

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/src/signed.rs
> +const DEFAULT_RSA_KEY_SIZE: u32 = 8192;
💪

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/src/signed.rs
> +    println!("{}", formatted_date_time);
`dbg!` ?

2021-12-10 15:39 UTC, efrisch commented on pyrsia_node/pyrsia_client_lib/src/signed.rs
> +#[derive(Deserialize, Serialize)]
`Debug`, `Clone` and `Copy` might also be good practice. https://doc.rust-lang.org/rust-by-example/trait/clone.html

2021-12-10 15:40 UTC, merged