Signing artifacts
pyrsia/pyrsia pull request #641
Opened 2022-05-01 11:42 UTC by AbhijithGanesh

## Description

Fixes pyrsia/pyrsia#511

This PR does provides an opportunity to sign artifacts by signing it with libp2p ed25519 keys and it 

## Screenshots (optional)

## PR Checklist

- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've included a good title and brief description along with how to review them.
- [ ] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [ ] I've built the code `cargo build --all-targets` successfully.
- [ ] I've run the unit tests `cargo test --workspace` and everything passes.
- [ ] I've made sure my rust toolchain is current `rustup update`.

2022-05-02 18:08 UTC, chb0github commented
I don't get the point of this code. It's 2 functions identical to the underlying code, which is implemented as a single line. So, help me understand purpose

2022-05-04 15:22 UTC, AbhijithGanesh commented
Currently, the functions don't take any default parameter, I was under the assumption public key will be shared and it will be passed as default value. The value will then be used to verify whenever the function is being called.

2022-05-09 07:39 UTC, MitaliBo requested changes

2022-05-09 07:39 UTC, MitaliBo commented on src/signed.rs
> +/*
To adhere with the project structure we want to move any any new modules in a directory and then create a mod file for that.

2022-05-09 07:39 UTC, MitaliBo commented on src/signed.rs
> +}
why do we want these wrapper functions ?

2022-05-12 17:25 UTC, betarelease commented
At this time we are still figuring out what signing means for Pyrsia (notes here - https://docs.google.com/document/d/1mOSMyZkM-HaKYnKNwk_Qr6t3331EZXHSQgp2L8dsjw4/edit#)

We plan to put this on hold for now and take this up again when we have a need for signing.

2022-07-25 18:44 UTC, betarelease commented
Closing this pull request after discussion during the sprint planning and has been stale for awhile.

2022-07-25 18:44 UTC, closed without merging