scripts and compose files for integration testing
pyrsia/pyrsia pull request #664
Opened 2022-05-06 17:23 UTC by tiainen

## Description

Fixes pyrsia/pyrsia#234

This PR adds scripts and the necessary docker files to start an integration test of the pyrsia node. To start the integration test, navigate to the `tests` directory and run: `./pyrsia-it-test.sh`.

It mainly works by leveraging docker compose and dind (docker-in-docker) containers. The docker compose consists of the following services:

 * two dind containers, where each registry mirror is configured to a pyrsia node
 * two pyrsia nodes
 * a bare debian container that runs the integration test

The dind containers are started up first. Afterwards we start up pyrsia node 1 and then pyrsia node 2. Finally, the integration test container is started which runs the script located at `tests/pyrsia-it.sh`. The script itself pulls the `alpine:3.15.4` image from the first docker container. Because of the registry mirror configuration, it downloads the image from pyrsia node 1. Since it is the first time that the image is requested, it is not yet available locally and therefore will be downloaded from docker.io. Then the script will pull the alpine image from the second docker container. Because of the registry mirror configuration, the download will happen from pyrsia node 2. This time the image is available in the pyrsia network (where pyrsia node 1 is a provider of the image) and hence the image is downloaded over the libp2p network from pyrsia node 1 instead of from docker.io.

Finally, the integration test script will verify the logs of the second pyrsia node to verify that the images was indeed succesfully downloaded over the libp2p network.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

2022-05-19 18:16 UTC, chb0github commented on Dockerfile
> +RUN <<EOT bash
mmm, normaly this is done

```
RUN apt-get update && apt-get install -y ca-certificates &&...
```

A heredoc might make sense if you're trying to do variable substitution, which you're not

2022-05-19 18:17 UTC, chb0github commented on Dockerfile
> +RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
multi-line this please

2022-05-19 18:18 UTC, chb0github commented on tests/docker-compose-it.yml
> +    image: docker:dind
Help me understand why this is needed. I mean, even docker recommends against this

2022-05-19 18:18 UTC, chb0github commented on tests/docker-compose-it.yml
> +    image: pyrsia/node-it
what is "pyrsia/node-it`

2022-05-19 18:19 UTC, chb0github commented on tests/docker-compose-it.yml
> +networks:
Why are they all on different networks?

2022-05-19 19:52 UTC, chb0github commented on tests/pyrsia-it-test.sh
> +    w1=$(docker-compose -f docker-compose-it.yml -p pyrsia-it logs docker1 docker2 | grep -F "API listen on [::]:2376" | wc -l)
Hmm, you know that if there is an error, this will never actually end, right?

2022-05-19 19:53 UTC, chb0github commented on tests/pyrsia-it-test.sh
> +    w2=$(docker-compose -f docker-compose-it.yml -p pyrsia-it logs pyrsia1 | grep -F "> Listen for p2p events" | wc -l)
I am not sure where this text comes from, but it's arbitrary log output from code which could change and you'd not know - and then this loop would go forever

2022-05-19 19:53 UTC, chb0github commented on tests/pyrsia-it-test.sh
> +
`set -e` always

2022-05-19 19:54 UTC, chb0github commented on tests/pyrsia-it-test.sh
> +#!/bin/bash
you should be using `#!/usr/bin/env bash` so as to pickup bash from wherever it's installed - make it more portable

2022-05-19 19:56 UTC, chb0github commented on tests/pyrsia-it-test.sh
> +v1=$(docker-compose -f docker-compose-it.yml -p pyrsia-it logs pyrsia2 | grep "Step 1: NO, alpine/3.15.4 does not exist in the metadata manager\\." | wc -l)
This is very opaque. If you're going to do this, then it should be:
1. run code
2. assert result

Not, run 10 tests and assert all 10. You want to know which failed and when. I have no idea what the different is between `v6` and `v9`

2022-05-19 19:57 UTC, chb0github requested changes
There are definitely ways to improve

2022-06-13 17:12 UTC, fishseabowl approved these changes
LGTM

2022-09-29 09:00 UTC, tiainen commented
Closing in favor of the work done here: https://github.com/pyrsia/pyrsia-integration-tests

2022-09-29 09:00 UTC, closed without merging