Refactor blockchain CLI: add -I argument to specify node index
pyrsia/pyrsia pull request #671
Opened 2022-05-09 20:39 UTC by fishseabowl

## Description

Fixes pyrsia/pyrsia#670

This PR add -I argument to specify node index. 

## Screenshots (optional)

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [x] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [ ] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

2022-05-09 20:49 UTC, chb0github commented on src/blockchain/examples/simple_node.rs
> +    let id_keys = create_ed25519_keypair(args.clone());
`create_ed25519_keypair` should not directly take the cli arg struct, but instead should just take the path since that's more portable

2022-05-09 20:50 UTC, chb0github requested changes
please change `create_ed25519_keypair` to take a string for the path

2022-05-09 22:30 UTC, prince-chrismc approved these changes
One less `TODO` 🚀

2022-05-11 21:20 UTC, chb0github approved these changes

2022-05-11 21:21 UTC, merged