Circuit Relay V2 client and DCUTR protocols for NAT Traversal
pyrsia/pyrsia pull request #712
Opened 2022-05-19 06:55 UTC by MitaliBo

## Description

Fixes #533 

This PR adds the behaviour of circuit relay v2 client and dcutr(direct connection upgrade through relay) which is needed for NAT Traversal either through relay or hole punching
## Screenshots (optional)

## PR Checklist

- [ ] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [ ] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/good_pr.md)
- [ ] I've included a good title and brief description along with how to review them.
- [ ] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).
- [ ] I've requested a review  from `pyrsia/collaborators`.

### Code Contributions

- [ ] I've built the code `cargo build --all-targets` successfully.
- [ ] I've run the unit tests `cargo test --workspace` and everything passes.
- [ ] I've made sure my rust toolchain is current `rustup update`.

2022-05-19 16:43 UTC, fishseabowl commented on src/network/client.rs
> +        receiver.await.expect("Sender not to be dropped.")
Please refer to PR #708.  It is better to propagate channel errors.

2022-05-19 16:46 UTC, prince-chrismc commented on src/network/client.rs
> +        receiver.await.expect("Sender not to be dropped.")
👍

2022-05-19 21:15 UTC, prince-chrismc reviewed
Some notes for my future self

2022-05-19 21:15 UTC, prince-chrismc commented on pyrsia_node/src/args/parser.rs
> +pub enum Mode {
This is the "Relay Mode" (not the node mode)

2022-05-19 21:15 UTC, prince-chrismc commented on pyrsia_node/src/args/parser.rs
> +    NoRelay,
This is the old "direct connection mode"

2022-05-19 21:15 UTC, prince-chrismc commented on src/network/client/command.rs
> +    ListenRelay {
This is the message routing component that needs to be handled

2022-05-19 21:15 UTC, prince-chrismc commented on src/network/client/command.rs
> +        sender: oneshot::Sender<Result<(), Box<dyn Error + Send>>>,
Should be new anyhow as @fishseabowl mentioned above

2022-05-19 21:22 UTC, prince-chrismc reviewed
The main inspiration has been https://github.com/libp2p/rust-libp2p/tree/master/protocols/dcutr/examples

2022-05-23 23:04 UTC, prince-chrismc commented on pyrsia_node/src/args/parser.rs
> +    /// The listening address
```suggestion
    /// The address of the relay server. (local address for `Listen` or remote address for `Dial`
```

2022-05-25 02:17 UTC, prince-chrismc approved these changes

2022-06-01 20:37 UTC, chb0github commented on pyrsia_node/src/main.rs
> +                    .expect("Listening should not fail");
Dial should work the same

2022-06-01 20:39 UTC, chb0github requested changes
See comments

2022-06-02 18:29 UTC, prince-chrismc commented on src/network/event_loop.rs
> +                let _ = match self.swarm.listen_on(addr.with(Protocol::P2pCircuit)) {
This is the convention being used the code today

![image](https://user-images.githubusercontent.com/16867443/171701015-8d3fe3d1-7f45-49e7-b09d-6e50009716ca.png)

2022-06-02 18:36 UTC, chb0github approved these changes
`let _` it be

2022-06-02 18:40 UTC, prince-chrismc commented
> `let _` it be

After chatting on slack, the usage is pretty wide spread so we opted to make a new issue #756

2022-06-03 18:46 UTC, merged