make keypair name and location configurable
pyrsia/pyrsia pull request #835
Opened 2022-07-06 22:29 UTC by sbtaylor15

## Description

Make the location of the key pair configurable so it is not in the artifact directory.

Fixes #831 

This PR makes the key pair configurable by using PYRSIA_KEYPAIR env var. This env var is the full file name for the key pair.  A new key pair will be generated if one does not exist.

## Screenshots (optional)

## PR Checklist

- [X] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [X] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [X] I've included a good title and brief description along with how to review them.
- [X] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [X] I've built the code `cargo build --all-targets` successfully.
- [X] I've run the unit tests `cargo test --workspace` and everything passes.
- [X] I've made sure my rust toolchain is current `rustup update`.

2022-07-07 09:56 UTC, tiainen commented on src/util/keypair_util.rs
> +    pub static ref KEYPAIR_FILENAME: String = {
Instead of the lazy static variable, can't we load the path from the environment variable in the `load_or_generate_ed25519()` function instead? Apart from the creation of the parent directory, I don't see a real use case for lazy static initialization. And you already took care of that part in the `save_ed25519()` function anyway.

2022-07-26 17:48 UTC, efrisch approved these changes
lgtm. 👍

2022-07-26 17:48 UTC, efrisch requested changes
Oops. Merge needed first.

2022-07-27 18:04 UTC, sbtaylor15 commented on src/util/keypair_util.rs
> +    pub static ref KEYPAIR_FILENAME: String = {
We cannot load the variable from inside of `load_or_generate_ed25519()` since we pass in different filenames/paths as part of the test cases parameters to `load_or_generate_ed25519()`.   The code is easier to understand using the lazy_static.

2022-07-28 11:32 UTC, tiainen commented on src/util/keypair_util.rs
> +    pub static ref KEYPAIR_FILENAME: String = {
Looks like we disagree on readability there. We can refactor the usage of `lazy_static` in another issue if needed.

2022-07-28 11:47 UTC, tiainen commented on src/network/p2p.rs
> +    let local_keypair = keypair_util::load_or_generate_ed25519(KEYPAIR_FILENAME.as_str());
You missed a change that was there in an earlier commit. Unfortunately, those changes got removed because of the forced push. Fortunately, I remembered: you'll need to update the use of `load_or_generate_ed25519` in `pyrsia_node/src/main.rs` (https://github.com/pyrsia/pyrsia/blob/main/pyrsia_node/src/main.rs#L133) as well to use KEYPAIR_FILENAME instead of ARTIFACTS_DIR.

2022-07-28 21:03 UTC, sbtaylor15 commented on src/network/p2p.rs
> +    let local_keypair = keypair_util::load_or_generate_ed25519(KEYPAIR_FILENAME.as_str());
@tiainen thanks for catching that.  Got introduced when I tried to remove the lasy_static.  All fixed now.

2022-07-29 06:53 UTC, tiainen approved these changes

2022-08-01 18:23 UTC, efrisch approved these changes
👍

2022-08-01 18:24 UTC, merged