AutoNAT Protocol Implementation
pyrsia/pyrsia pull request #848
Opened 2022-07-12 13:19 UTC by efrisch

## Description

Fixes pyrsia/pyrsia#711

This PR adds AutoNAT support by integrating with [libp2p-autonat](https://crates.io/crates/libp2p-autonat) and it can be reviewed; you can also test the changes by connecting to gcp-sandbox

## Screenshots (optional)

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

2022-07-18 18:45 UTC, fishseabowl approved these changes
LGTM

2022-07-19 14:12 UTC, tiainen requested changes

2022-07-19 14:12 UTC, tiainen commented on src/network/p2p.rs
> +    swarm
I propose to change this call to be initiated via the p2p client, as is currently done for instance for [listening](https://github.com/pyrsia/pyrsia/blob/e0f36b04e2f8333f72b00e657f301a249684399a/src/network/client.rs#L77) and [dialing](https://github.com/pyrsia/pyrsia/blob/e0f36b04e2f8333f72b00e657f301a249684399a/src/network/client.rs#L91). It could be called `probe` or `add_probe_address` and take the PeerId and Multiaddr to add for probing as a parameter.

```
pub async fn add_probe_address(&mut self, peer_id: &PeerId, probe_addr: &Multiaddr) -> anyhow::Result<()> {
    self.sender
        .send(Command::AddProbe {
            peer_id: *peer_id,
            probe_addr: probe_addr.clone(),
        })
        .await
}
```

And then handle the extra command in the event handler (src/network/event_loop.rs):
```
Command::AddProbe { peer_id, probe_addr } => {
    self.swarm
        .behaviour_mut()
        .auto_nat
        .add_server(peer_id, Some(probe_addr));
```

2022-07-19 14:12 UTC, tiainen commented on src/network/p2p.rs
> +    let config: CliConfig = get_config().unwrap();
This panics when `p2p_port` is not defined in the local pyrsia config. I would remove it from the CliConfig and instead pass it as an argument to the pyrsia node. Akin to the `--peer` argument to dial another pyrsia node, I would add support for an optional argument `--probe <address>` that, when provided will add the address to the autonat behavior. See my comment about that a bit below.

2022-07-25 08:02 UTC, tiainen commented on src/network/event_loop.rs
> +                sender: _,
You'll need to call `sender.send()` after the server has been added. Otherwise the receiver side in the network client will wait indefinitely. As mentioned in the other comment, we can just send the unit type `()` to notify the receiver that the command was successfully handled: `sender.send(())`.

2022-08-04 00:34 UTC, sbtaylor15 submitted a review, later dismissed
/lgtm

2022-08-05 17:25 UTC, fishseabowl commented on pyrsia_node/src/main.rs
> +        info!("Invoking dial");
What happens if both probe addr and peer addr exist in the CLI? Just ignore the peer addr?

2022-08-05 17:31 UTC, fishseabowl commented on src/blockchain/src/network.rs
> -    tcp::{GenTcpConfig, TokioTcpTransport},
It's better to keep lines 44-45 as a reminder to add `tcp-tokio` feature

2022-08-05 17:47 UTC, efrisch commented on src/network/event_loop.rs
> +                sender: _,
@tiainen This is ready for re-review.

2022-08-05 18:04 UTC, efrisch commented on pyrsia_node/src/main.rs
> +        info!("Invoking dial");
Yes. Peer should go away long term. Or probe should replace it. Long term. Note the next pr will make it optional, and default to "boot.pyrsia.link"

2022-08-08 18:03 UTC, betarelease commented
@efrisch Is this a PR for #584 ? Can we mark it as such?

2022-08-11 16:28 UTC, sbtaylor15 approved these changes
/lgtm

2022-08-11 16:34 UTC, fishseabowl approved these changes

2022-08-14 19:29 UTC, johanvos approved these changes

2022-08-15 16:50 UTC, merged