Upgrade method tcp::TokioTcpConfig to tcp::TokioTcpTransport
pyrsia/pyrsia pull request #858
Opened 2022-07-14 21:40 UTC by fishseabowl

## Description

Fixes pyrsia/pyrsia#843

This PR changes the method tcp::TokioTcpConfig to tcp::TokioTcpTransport to upgrade to libp2p 0.46.1

## Screenshots (optional)

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.
- [x] I've made sure my rust toolchain is current `rustup update`.

2022-07-15 07:35 UTC, tiainen approved these changes

2022-07-15 18:08 UTC, efrisch requested changes
Hold for now.

2022-07-15 18:08 UTC, efrisch commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
Let's stick with `libp2p = { version = "0.45.1", features=["dns-tokio", "tcp-tokio"]}` for now. Because this breaks libp2p-autonat 0.5.0 (which is still the current version).

2022-07-18 12:53 UTC, tiainen commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
Can you explain how it breaks autonat? From the [libp2p dependencies](https://crates.io/crates/libp2p/0.46.1/dependencies), I can see that `libp2p:0.46.1` depends on `libp2p-autonat:0.5.0` already? I also see that the NAT draft PR [manually includes a dependency](https://github.com/pyrsia/pyrsia/pull/848/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R49) to `libp2p-autonat:0.5.0`, which should not be needed, because the feature is [included by default](https://docs.rs/crate/libp2p/latest/features)?

2022-07-18 19:05 UTC, efrisch commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
@tiainen  @sbtaylor15 When I ran it with libp2p:0.46.1 it broke the build on my branch. Revisiting now, because the build is broken on my branch (again).

2022-07-19 11:35 UTC, tiainen commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
The update does indeed break the build. That's the reason for this PR, to fix the breaking changes that were introduced with libp2p:0.46.1. When we merge this PR, you can simply merge these changes into your branch and your code should build without problems. Then you can also remove the hard dependency on libp2p-autonat 0.5.0, because libp2p 0.46.1 already depends on that version.

2022-07-19 11:46 UTC, efrisch commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
@tiainen  @sbtaylor15  I merged these changes into my branch last week, and it triggered build errors relating to libp2p_core traits not being compatible with libp2p traits of the same names. I will try it again today. Perhaps I did something else incorrectly with that merge.

2022-07-19 13:03 UTC, efrisch commented on Cargo.toml
> +libp2p = { version = "0.46.1", features=["dns-tokio", "tcp-tokio"]}
> I've tried it on your branch earlier today and managed to build it.

`cargo build` works. `cargo build --workspace --all-targets` fails. With errors below.

2022-07-19 13:14 UTC, efrisch approved these changes
Joeri helped me determine what I was doing wrong. This merges cleanly with the autonat changes on the correct branch. 👍

2022-07-19 13:14 UTC, merged