Removes duplicated document and section from website
pyrsia/pyrsia pull request #926
Opened 2022-08-04 20:35 UTC by betarelease

## Description

This PR does removes duplicate document and section from the website

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

2022-08-04 21:09 UTC, fishseabowl approved these changes

2022-08-04 21:38 UTC, dasmanas requested changes
In local setup I found an error `build failed to run custom build command for prost-build v#.#.#`
By installing protobuf I able to overcome.
Refer http://google.github.io/proto-lens/installing-protoc.html for further information.

2022-08-05 06:46 UTC, tiainen approved these changes

2022-08-05 16:28 UTC, dasmanas approved these changes

2022-08-05 17:24 UTC, merged